# Classification model using Multilayer Perceptron

### 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

### 2. Upload RNA data

In [2]:
path ='../../../../Data_preprocessing/Prediction PFS/RNA+Clinic joined/New/Clinical_data_and_RNA_30_Features_PFS.csv'
data = pd.read_csv(path)
data.head(5)

Unnamed: 0                                RNA_ID   Age  Sarc  Rhab  \
0           0  G138701_RCCBMS-00020-T_v1_RNA_OnPrem  62.0   0.0   0.0   
1           1  G138701_RCCBMS-00097-T_v1_RNA_OnPrem  67.0   0.0   0.0   
2           2  G138701_RCCBMS-00141-T_v1_RNA_OnPrem  62.0   0.0   0.0   
3           3  G138701_RCCBMS-00099-T_v1_RNA_OnPrem  60.0   0.0   0.0   
4           4  G138701_RCCBMS-00163-T_v1_RNA_OnPrem  76.0   0.0   0.0   

   Number_of_Prior_Therapies  \
0                        2.0   
1                        2.0   
2                        1.0   
3                        3.0   
4                        2.0   

   Days_from_TumorSample_Collection_and_Start_of_Trial_Therapy  \
0                                              962.0             
1                                              254.0             
2                                              800.0             
3                                              790.0             
4                                             1241.0             

   Tumor_Shrinkage        PFS  TM_TC_Ratio  ...  RP11-96O20.4  RP5-827C21.1  \
0       -16.406250  12.164384     0.766909  ...      21.18753      27.40814   
1       -40.000000   5.490411     0.773269  ...      21.18753      29.25015   
2       -89.436620  61.906849     1.782859  ...      21.18753      23.03429   
3        11.787072   1.249315     5.890573  ...      21.18753      23.03429   
4         0.000000   5.654795     1.374775  ...      21.18753      23.03429   

   RPS12P26   SDR42E1  SNORD113-5    TARBP2    TRAV41  TRIM43B   VN2R17P  \
0  31.71139  30.26124    21.32743  29.60417  22.22154  21.9744  21.12857   
1  29.15373  29.12730    21.32743  29.61188  22.22154  21.9744  21.12857   
2  29.37858  27.22907    21.32743  31.90343  22.22154  21.9744  21.12857   
3  30.19136  22.83731    21.32743  30.35424  22.22154  21.9744  21.12857   
4  31.82172  22.83731    21.32743  31.60946  22.22154  21.9744  21.12857   

        XPC  
0  32.24472  
1  32.15619  
2  31.86536  
3  31.63561  
4  33.12717  

[5 rows x 57 columns]

In [3]:
X = data[['AC005307.1', 'ATP5G2P1', 'DLGAP4', 'EIF4A1P9', 'FAM172BP', 'FAM224A', 'GJA9', 'GPR155', 'GYPE', 'IL25', 'KLHL5', 'LANCL1-AS1', 'LEMD1', 'PCMT1', 'RP11-120J4.1', 'RP11-20G6.3', 'RP11-349G13.2', 'RP11-374M1.2', 'RP11-536C10.21', 'RP11-95G17.2', 'RP11-96O20.4', 'RP5-827C21.1', 'RPS12P26', 'SDR42E1', 'SNORD113-5', 'TARBP2', 'TRAV41', 'TRIM43B', 'VN2R17P', 'XPC']] #Seleccionamos todas las columnas quitando la columna Unnamed (id de la fila ) y la columna Target.

Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    elif data.PFS[i]<6:
        Y.append(1)
    else:
        Y.append(2)# If PFS is over 3 months, I will consider it as Responder (R)


print(X)
print('Numero de pacientes: ',len(Y))

     AC005307.1   ATP5G2P1    DLGAP4  EIF4A1P9  FAM172BP   FAM224A      GJA9  \
0     21.055379  21.300337  34.54982  21.37925  21.62929  21.12373  29.68286   
1     21.055379  21.300337  34.06647  21.37925  21.62929  21.12373  26.80539   
2     21.055379  21.300337  34.42561  25.08766  29.29206  21.12373  30.09292   
3     21.055379  21.300337  34.41176  26.76156  21.62929  21.12373  29.29223   
4     21.055379  21.300337  34.29088  21.37925  21.62929  21.12373  32.00382   
..          ...        ...       ...       ...       ...       ...       ...   
176   20.944668  21.624881  34.55658  21.78113  21.49653  20.98542  28.18967   
177   20.944668  21.624881  33.15506  21.78113  21.49653  20.98542  28.18967   
178   20.944668  21.624881  34.68047  21.78113  25.64475  23.49110  28.18967   
179   20.944668  21.624881  35.60014  21.78113  21.49653  20.98542  33.92530   
180   20.944668  21.624881  35.23053  21.78113  21.49653  20.98542  28.18967   

       GPR155      GYPE      IL25  ... 

### 3. Train-Test dataset split

In [4]:
XTrain, XTest, yTrain, yTest = train_test_split(X, Y, test_size=0.15, random_state=125, stratify=Y)

print('Training set size:', len(XTrain))
print('Target column size of the training set:', len(yTrain))
print('Test set size:', len(XTest))
print('Target column size of the test set:', len(yTest))

Training set size: 153
Target column size of the training set: 153
Test set size: 28
Target column size of the test set: 28


In [5]:
param_grid = {'max_iter': [200, 500, 1000],
            'activation': ['identity', 'logistic', 'tanh', 'relu'],
            'random_state': [125],
            'max_fun': [300, 500,1000, 5000, 10000, 15000, 20000],
            'hidden_layer_sizes': [3,5],
            'solver': ['lbfgs']}

# I created a GridSearchCV which allows us to systematically evaluate and select the parameters of our model.
# By indicating a model and the parameters to test, you can evaluate the performance of the first one based on the
# seconds through cross validation.
clf = GridSearchCV(MLPClassifier(), param_grid, cv =5)

clf.fit(XTrain , yTrain)


C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, sel

GridSearchCV(cv=5, estimator=MLPClassifier(),
             param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'],
                         'hidden_layer_sizes': [3, 5],
                         'max_fun': [300, 500, 1000, 5000, 10000, 15000, 20000],
                         'max_iter': [200, 500, 1000], 'random_state': [125],
                         'solver': ['lbfgs']})

In [6]:
print("Best estimate of parameters according to GridSearchCV:")
model = clf.best_estimator_
# Fit the model with the best parameters
model.fit(XTrain , yTrain)

Best estimate of parameters according to GridSearchCV:


C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='identity', hidden_layer_sizes=3, max_fun=5000,
              max_iter=1000, random_state=125, solver='lbfgs')

In [7]:
print("Best result of the cross validation of the model with the best paramters:" +str(clf.best_score_))

Best result of the cross validation of the model with the best paramters:0.6920430107526881


### 5. Prediction

In [8]:
# Making predictions with the optimal model on the training dataset
yhatTrain = model.predict(XTrain)
contTrain = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTrain),1) :
    if (yhatTrain[i] == yTrain[i]):
        contTrain = contTrain + 1

In [9]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(XTest)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTest),1) :
    if (yhatTest[i] == yTest[i]):
        contTest = contTest + 1


### 6. Results

In [10]:
print('Final accuracy on the training dataset:' + str(contTrain/len(yTrain)))
print('Final accuracy on the testing dataset: ' + str(contTest/len(yTest)))

Final accuracy on the training dataset:0.8562091503267973
Final accuracy on the testing dataset: 0.6785714285714286


In [11]:
from sklearn.metrics import classification_report,confusion_matrix

print('----------------Confusion Matrix (Training)------------------')
print(confusion_matrix(yTrain,yhatTrain))
print('Input data:  ' + str(np.array(yTrain)))
print('Prediction:        ' +str(yhatTrain))

----------------Confusion Matrix (Training)------------------
[[69  1  2]
 [ 2 15  9]
 [ 2  6 47]]
Input data:  [1 2 2 2 0 2 2 2 0 0 0 2 0 0 0 2 2 0 0 0 2 0 2 0 0 0 2 1 0 0 0 1 0 0 0 0 1
 1 1 2 2 2 2 0 1 2 0 0 2 2 1 2 1 0 2 0 2 2 2 0 0 2 0 2 2 0 2 2 0 0 0 0 0 0
 1 2 2 0 2 0 0 0 2 0 0 0 1 0 0 1 0 2 2 0 0 1 1 2 1 2 1 0 0 2 0 2 0 0 1 0 1
 0 0 2 0 0 2 2 2 2 1 0 2 2 2 1 0 0 1 0 0 1 0 2 2 1 0 2 0 0 2 0 1 0 0 0 2 2
 2 1 2 0 1]
Prediction:        [1 1 2 2 0 2 2 2 0 0 0 2 0 0 0 2 2 0 0 0 2 0 2 0 0 0 2 2 1 0 0 1 0 0 0 0 2
 0 1 2 2 2 2 0 1 2 0 0 2 2 1 2 2 0 2 0 2 2 2 0 0 2 0 2 2 0 2 2 0 0 0 2 0 0
 1 1 2 0 2 0 0 0 2 0 0 0 1 0 0 2 0 1 0 0 0 1 2 2 2 2 0 0 0 2 0 2 0 0 1 0 1
 0 0 1 0 0 0 2 1 2 2 2 2 2 2 1 0 0 2 0 0 1 0 2 1 1 0 2 0 0 2 0 1 0 0 0 2 2
 2 1 2 0 2]


In [12]:
print(classification_report(yTrain,yhatTrain))

              precision    recall  f1-score   support

           0       0.95      0.96      0.95        72
           1       0.68      0.58      0.62        26
           2       0.81      0.85      0.83        55

    accuracy                           0.86       153
   macro avg       0.81      0.80      0.80       153
weighted avg       0.85      0.86      0.85       153



In [13]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(yTest,yhatTest))
print('Input data:  ' + str(np.array(yTest)))
print('Prediction:        ' +str(yhatTest))

----------------Confusion Matrix (Test)------------------
[[11  1  1]
 [ 0  0  5]
 [ 0  2  8]]
Input data:  [0 2 2 1 2 0 2 0 0 1 0 1 2 2 0 2 0 0 1 2 0 0 0 2 2 1 0 0]
Prediction:        [0 2 2 2 1 2 2 0 0 2 0 2 2 2 0 2 0 0 2 1 0 0 0 2 2 2 0 1]


In [14]:
print(classification_report(yTest,yhatTest))

              precision    recall  f1-score   support

           0       1.00      0.85      0.92        13
           1       0.00      0.00      0.00         5
           2       0.57      0.80      0.67        10

    accuracy                           0.68        28
   macro avg       0.52      0.55      0.53        28
weighted avg       0.67      0.68      0.66        28

