# Classification model using Decision Tree

### 1. Import libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV

### 2. Upload Clinic data

In [5]:
path ='../../../../Data_preprocessing/Prediction PFS/RNA+Clinic joined/New/Clinical_data_and_RNA_22_Features_PFS.csv'
data = pd.read_csv(path)
data.head()

Unnamed: 0                                RNA_ID   Age  Sarc  Rhab  \
0           0  G138701_RCCBMS-00020-T_v1_RNA_OnPrem  62.0   0.0   0.0   
1           1  G138701_RCCBMS-00097-T_v1_RNA_OnPrem  67.0   0.0   0.0   
2           2  G138701_RCCBMS-00141-T_v1_RNA_OnPrem  62.0   0.0   0.0   
3           3  G138701_RCCBMS-00099-T_v1_RNA_OnPrem  60.0   0.0   0.0   
4           4  G138701_RCCBMS-00163-T_v1_RNA_OnPrem  76.0   0.0   0.0   

   Number_of_Prior_Therapies  \
0                        2.0   
1                        2.0   
2                        1.0   
3                        3.0   
4                        2.0   

   Days_from_TumorSample_Collection_and_Start_of_Trial_Therapy  \
0                                              962.0             
1                                              254.0             
2                                              800.0             
3                                              790.0             
4                                             1241.0             

   Tumor_Shrinkage        PFS  TM_TC_Ratio  ...  CTC-523E23.14  CTD-2050N2.1  \
0       -16.406250  12.164384     0.766909  ...       21.01388      21.02976   
1       -40.000000   5.490411     0.773269  ...       21.01388      21.02976   
2       -89.436620  61.906849     1.782859  ...       21.01388      21.02976   
3        11.787072   1.249315     5.890573  ...       21.01388      21.02976   
4         0.000000   5.654795     1.374775  ...       21.01388      21.02976   

    DDX43P2   GLUD1P4  LINC01446  LINC01602    RNF212  RP11-123J14.1  \
0  20.99861  21.07023   20.99572   21.03733  30.21949       21.00825   
1  20.99861  21.07023   22.16510   21.03733  30.76723       21.00825   
2  20.99861  21.07023   20.99572   21.03733  27.61482       21.00825   
3  20.99861  21.07023   20.99572   21.03733  32.89925       21.00825   
4  20.99861  21.07023   20.99572   21.03733  23.21111       21.00825   

   RP11-326N17.1  RP11-353N14.5  
0       20.99301       21.10114  
1       20.99301       21.10114  
2       20.99301       21.10114  
3       20.99301       21.10114  
4       20.99301       21.10114  

[5 rows x 49 columns]

In [6]:
data = data[['RNA_ID','MSKCC_FAVORABLE', 'MSKCC_INTERMEDIATE', 'MSKCC_NA', 'MSKCC_POOR','PFS','AC006007.1',
'AC006262.10',
'AC006296.2',
'AC010729.2',
'AC012363.13',
'AC013436.6',
'AC023128.1',
'AC078842.3',
'AC091814.2',
'AP000997.2',
'AP006285.7',
'CTC-436K13.4',
'CTC-523E23.14',
'CTD-2050N2.1',
'DDX43P2',
'GLUD1P4',
'LINC01446',
'LINC01602',
'RNF212',
'RP11-123J14.1',
'RP11-326N17.1',
'RP11-353N14.5']]
data.head()

RNA_ID  MSKCC_FAVORABLE  MSKCC_INTERMEDIATE  \
0  G138701_RCCBMS-00020-T_v1_RNA_OnPrem                1                   0   
1  G138701_RCCBMS-00097-T_v1_RNA_OnPrem                1                   0   
2  G138701_RCCBMS-00141-T_v1_RNA_OnPrem                0                   0   
3  G138701_RCCBMS-00099-T_v1_RNA_OnPrem                1                   0   
4  G138701_RCCBMS-00163-T_v1_RNA_OnPrem                0                   1   

   MSKCC_NA  MSKCC_POOR        PFS  AC006007.1  AC006262.10  AC006296.2  \
0         0           0  12.164384   21.024011    20.998508    21.01321   
1         0           0   5.490411   21.024011    20.998508    21.01321   
2         0           1  61.906849   21.024011    20.998508    21.01321   
3         0           0   1.249315   21.024011    20.998508    21.01321   
4         0           0   5.654795   21.024011    20.998508    21.01321   

   AC010729.2  ...  CTC-523E23.14  CTD-2050N2.1   DDX43P2   GLUD1P4  \
0   21.050318  ...       21.01388      21.02976  20.99861  21.07023   
1   21.050318  ...       21.01388      21.02976  20.99861  21.07023   
2   21.050318  ...       21.01388      21.02976  20.99861  21.07023   
3   21.050318  ...       21.01388      21.02976  20.99861  21.07023   
4   21.050318  ...       21.01388      21.02976  20.99861  21.07023   

   LINC01446  LINC01602    RNF212  RP11-123J14.1  RP11-326N17.1  RP11-353N14.5  
0   20.99572   21.03733  30.21949       21.00825       20.99301       21.10114  
1   22.16510   21.03733  30.76723       21.00825       20.99301       21.10114  
2   20.99572   21.03733  27.61482       21.00825       20.99301       21.10114  
3   20.99572   21.03733  32.89925       21.00825       20.99301       21.10114  
4   20.99572   21.03733  23.21111       21.00825       20.99301       21.10114  

[5 rows x 28 columns]

In [7]:
Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    elif data.PFS[i]<6: # If PFS is over 6 months, I will consider it as Responder (R)
        Y.append(1)
    else:
        Y.append(2) # If PFS is between 3 and 6 months, I will consider it as SemiResponder (SR)
        

# As I won't need this columns any more, I deleted them.
data = data.drop('PFS', axis=1)
data = data.drop('RNA_ID', axis=1)

X = data.iloc[:,0:36] # I selected all the columns by removing the Unnamed column (row id) and the Target column.

print(X)
print('Numero de pacientes: ',len(Y))

     MSKCC_FAVORABLE  MSKCC_INTERMEDIATE  MSKCC_NA  MSKCC_POOR  AC006007.1  \
0                  1                   0         0           0   21.024011   
1                  1                   0         0           0   21.024011   
2                  0                   0         0           1   21.024011   
3                  1                   0         0           0   21.024011   
4                  0                   1         0           0   21.024011   
..               ...                 ...       ...         ...         ...   
176                0                   0         1           0   20.959318   
177                0                   0         1           0   20.959318   
178                0                   0         1           0   20.959318   
179                0                   0         1           0   20.959318   
180                0                   0         1           0   20.959318   

     AC006262.10  AC006296.2  AC010729.2  AC012363.13  AC013436

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=125)


print('Training set size:', len(X_train))
print('Target column size of the training set:', len(y_train))
print('Test set size:', len(X_test))
print('Target column size of the test set:', len(y_test))

Training set size: 144
Target column size of the training set: 144
Test set size: 37
Target column size of the test set: 37


### 4. Select the parameters of the model and fit it

In [9]:
param_grid = {'C': [1,2,5,7,10],
            'solver': ['newton-cg','liblinear'],  
            'max_iter':[20000,50000,100000],
            'random_state':[125]}

# Creamos un GridSearchCV que permite evaluar y seleccionar de forma sistemática los parámetros de nuestro modelo. 
# Indicándole un modelo y los parámetros a probar, puede evaluar el rendimiento del primero en función de los 
# segundos mediante validación cruzada.  
clf = GridSearchCV(LogisticRegression(), param_grid, cv = 5)
clf.fit(X_train , y_train)

C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\optimize\linesearch.py:478: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scipy\optimize\linesearch.py:478: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 5, 7, 10],
                         'max_iter': [20000, 50000, 100000],
                         'random_state': [125],
                         'solver': ['newton-cg', 'liblinear']})

In [10]:
print("Best estimate of parameters according to GridSearchCV:")
model = clf.best_estimator_
# Fit the model with the best parameters
model.fit(X_train , y_train)

Best estimate of parameters according to GridSearchCV:


LogisticRegression(C=1, max_iter=20000, random_state=125, solver='newton-cg')

In [11]:
print("Best result of the cross validation of the model with the best paramters:" +str(clf.best_score_))

Best result of the cross validation of the model with the best paramters:0.46600985221674873


In [12]:
# Making predictions with the optimal model on the training dataset
yhatTrain = model.predict(X_train)
contTrain = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(y_train),1) :
    if (yhatTrain[i] == y_train[i]):
        contTrain = contTrain + 1

In [13]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(X_test)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(y_test),1) :
    if (yhatTest[i] == y_test[i]):
        contTest = contTest + 1

In [14]:
print('Final accuracy on the training dataset:' + str(contTrain/len(y_train)))
print('Final accuracy on the testing dataset: ' + str(contTest/len(y_test)))

Final accuracy on the training dataset:0.5763888888888888
Final accuracy on the testing dataset: 0.40540540540540543


In [15]:
from sklearn.metrics import classification_report,confusion_matrix

print('----------------Confusion Matrix (Training)------------------')
print(confusion_matrix(y_train,yhatTrain))
print('Input data:  ' + str(np.array(y_train)))
print('Prediction:        ' +str(yhatTrain))

----------------Confusion Matrix (Training)------------------
[[41  0 24]
 [10  4 14]
 [12  1 38]]
Input data:  [0 2 1 1 1 1 0 2 0 1 2 2 1 0 2 0 2 0 0 0 2 1 0 0 2 2 0 1 0 0 1 1 0 2 1 0 1
 2 0 2 2 0 0 1 0 1 1 0 1 0 0 1 0 0 0 2 0 2 0 2 1 0 2 2 0 2 2 2 0 2 0 2 0 2
 2 0 0 2 0 0 1 2 1 0 0 0 0 2 1 2 2 0 0 2 2 2 2 0 0 0 2 0 2 0 0 0 0 1 0 2 0
 2 0 2 1 0 0 0 0 1 2 2 0 2 0 2 2 0 1 2 0 1 2 0 0 2 2 1 2 1 2 2 0 0]
Prediction:        [0 2 2 2 0 0 0 0 2 0 2 2 2 2 2 0 0 0 0 0 2 2 2 0 2 0 2 0 0 0 2 0 0 2 2 0 2
 2 2 2 2 0 0 2 0 1 0 0 0 0 2 2 2 0 2 2 0 2 0 2 0 0 2 2 2 2 0 2 2 2 2 2 0 2
 2 2 0 0 0 2 2 0 1 2 0 0 0 2 2 2 0 2 0 0 1 2 2 0 2 2 2 0 2 2 2 0 0 2 0 2 2
 0 0 2 2 0 0 0 2 2 2 2 2 2 0 2 0 0 1 2 2 1 2 2 0 0 0 0 2 0 2 2 0 0]


In [16]:
print(classification_report(y_train,yhatTrain))

              precision    recall  f1-score   support

           0       0.65      0.63      0.64        65
           1       0.80      0.14      0.24        28
           2       0.50      0.75      0.60        51

    accuracy                           0.58       144
   macro avg       0.65      0.51      0.49       144
weighted avg       0.63      0.58      0.55       144



In [17]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(y_test,yhatTest))
print('Input data:  ' + str(np.array(y_test)))
print('Prediction:        ' +str(yhatTest))

----------------Confusion Matrix (Test)------------------
[[ 8  2 10]
 [ 1  0  2]
 [ 5  2  7]]
Input data:  [1 0 0 2 2 1 0 2 2 2 0 0 0 0 0 0 2 0 1 0 0 0 0 2 0 0 2 2 2 0 0 2 0 0 2 2 2]
Prediction:        [2 2 2 0 2 0 0 2 2 0 0 2 0 0 0 2 0 2 2 1 2 2 2 1 0 0 2 2 0 0 1 2 2 2 0 2 1]


In [18]:
print(classification_report(y_test, yhatTest))

              precision    recall  f1-score   support

           0       0.57      0.40      0.47        20
           1       0.00      0.00      0.00         3
           2       0.37      0.50      0.42        14

    accuracy                           0.41        37
   macro avg       0.31      0.30      0.30        37
weighted avg       0.45      0.41      0.41        37



*Everolimus test*

In [19]:
path ='../../../../Data_preprocessing/Testing with everolimus/RNA+Clinic joined/Clinical_data_and_RNA_30_Features_everolimus.csv'
data = pd.read_csv(path)
data = data[['RNA_ID','MSKCC_FAVORABLE', 'MSKCC_INTERMEDIATE', 'MSKCC_NA', 'MSKCC_POOR','PFS','AC005307.1', 'ATP5G2P1', 'DLGAP4', 'EIF4A1P9', 'FAM172BP', 'FAM224A', 'GJA9', 'GPR155', 'GYPE', 'IL25', 'KLHL5', 'LANCL1-AS1', 'LEMD1', 'PCMT1', 'RP11-120J4.1', 'RP11-20G6.3', 'RP11-349G13.2', 'RP11-374M1.2', 'RP11-536C10.21', 'RP11-95G17.2', 'RP11-96O20.4', 'RP5-827C21.1', 'RPS12P26', 'SDR42E1', 'SNORD113-5', 'TARBP2', 'TRAV41', 'TRIM43B', 'VN2R17P', 'XPC']]

Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    elif data.PFS[i]<6:
        Y.append(1)
    else:
        Y.append(2)# If PFS is over 3 months, I will consider it as Responder (R)
data=data.drop([ 'PFS', 'RNA_ID'], axis=1)

FileNotFoundError: [Errno 2] No such file or directory: '../../../../Data_preprocessing/Testing with everolimus/RNA+Clinic joined/Clinical_data_and_RNA_30_Features_everolimus.csv'

In [ ]:
data.head(5)

In [ ]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(data)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(Y),1) :
    if (yhatTest[i] == Y[i]):
        contTest = contTest + 1

print('Final accuracy on the testing dataset: ' + str(contTest/len(Y)))

In [ ]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(Y,yhatTest))
print('Input data:  ' + str(np.array(Y)))
print('Prediction:        ' +str(yhatTest))
print(classification_report(Y,yhatTest))