# Classification model using Multilayer Perceptron

### 1. Import libraries

In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

### 2. Upload Clinic data

In [7]:
path ="../../../Data_preprocessing/RNA_post_autoencoder/encoded_data_multiclass.csv"
data = pd.read_csv(path)
data.reset_index
data.round(4)
data=data.iloc[:,1:440  ] 
data.head()

Target         0         1         2         3         4         5  \
0       1 -0.315205 -0.407536  0.531673  0.808408 -0.810542  0.193779   
1       0 -0.399706 -0.359715  0.589118  0.689009 -0.934274  0.590328   
2       2 -0.257777  0.017325 -0.369965  0.256681 -0.647283 -0.009628   
3       0  0.193269 -0.121839 -0.275106  0.063980 -0.259090 -0.195940   
4       2 -0.054664 -0.326593 -0.267536  0.490474 -0.725889 -0.157597   

          6         7         8  ...       428       429       430       431  \
0  0.034024 -0.164311  0.014579  ...  0.646639 -0.484226  0.024023  0.428195   
1  0.000470 -0.579490 -0.014040  ...  0.367153 -0.127431  0.453080  0.222101   
2  0.178241  0.039518 -0.395371  ... -0.180099  0.149861  0.336687  0.759315   
3  0.075242  0.029794  0.122252  ...  0.021265  0.002938  0.010013  0.112763   
4  0.261997  0.182627 -0.072347  ...  0.146497 -0.214596  0.316881  0.412167   

        432       433       434       435       436       437  
0 -0.997664 -0.198929  0.558472 -0.711090 -0.625051  1.313173  
1  0.063686 -0.350376  0.585483 -0.723964 -0.614908  1.041820  
2 -0.011072  0.195970  0.454717  0.462148 -0.548280  0.754466  
3  0.223452 -0.481063  0.166170  0.020349 -0.113602 -0.069602  
4  0.322099 -0.438647  0.382818 -0.143397 -0.469160  0.382200  

[5 rows x 439 columns]

In [8]:
Y = data.Target # Target column

X = data.iloc[:,1:439] # I selected all the columns by removing the Unnamed column (row id) and the Target column.


print(X)
print('Numero de pacientes: ',len(Y))

            0         1         2         3         4         5         6  \
0   -0.315205 -0.407536  0.531673  0.808408 -0.810542  0.193779  0.034024   
1   -0.399706 -0.359715  0.589118  0.689009 -0.934274  0.590328  0.000470   
2   -0.257777  0.017325 -0.369965  0.256681 -0.647283 -0.009628  0.178241   
3    0.193269 -0.121839 -0.275106  0.063980 -0.259090 -0.195940  0.075242   
4   -0.054664 -0.326593 -0.267536  0.490474 -0.725889 -0.157597  0.261997   
..        ...       ...       ...       ...       ...       ...       ...   
176  0.015191 -0.250067 -0.247737  0.428315 -0.673884 -0.122022  0.161610   
177  0.025750 -0.248474 -0.427581  0.390085 -0.543150 -0.102631  0.184679   
178 -0.380961 -0.304403  0.498039  0.549402  0.040175  0.282321 -0.007317   
179 -0.394782 -0.050161  0.336075  0.524383 -0.065044  0.317751 -0.014208   
180 -0.000122 -0.274288 -0.315658  0.305076 -0.167984 -0.064459  0.178613   

            7         8         9  ...       428       429       430  \
0  

### 3. Train-Test dataset split

In [9]:
XTrain, XTest, yTrain, yTest = train_test_split(X, Y, test_size=0.20, random_state=125, stratify=Y)
yTrain=yTrain.to_numpy()
yTest=yTest.to_numpy()
print('Training set size:', len(XTrain))
print('Target column size of the training set:', len(yTrain))
print('Test set size:', len(XTest))
print('Target column size of the test set:', len(yTest))

Training set size: 144
Target column size of the training set: 144
Test set size: 37
Target column size of the test set: 37


In [10]:
param_grid = {'max_iter': [200000, 500000, 10000000],
            'activation': ['identity', 'logistic', 'tanh', 'relu'],
            'random_state': [125],
            'max_fun': [300, 500,1000, 5000, 10000, 15000, 20000],
            'hidden_layer_sizes': [3,5],
            'solver': ['lbfgs']}

# I created a GridSearchCV which allows us to systematically evaluate and select the parameters of our model.
# By indicating a model and the parameters to test, you can evaluate the performance of the first one based on the
# seconds through cross validation.
clf = GridSearchCV(MLPClassifier(), param_grid, cv =5)

clf.fit(XTrain , yTrain)


C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lb

GridSearchCV(cv=5, estimator=MLPClassifier(),
             param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'],
                         'hidden_layer_sizes': [3, 5],
                         'max_fun': [300, 500, 1000, 5000, 10000, 15000, 20000],
                         'max_iter': [200000, 500000, 10000000],
                         'random_state': [125], 'solver': ['lbfgs']})

In [11]:
print("Best estimate of parameters according to GridSearchCV:")
print(clf.best_estimator_)
# Fit the model with the best parameters
model = clf.best_estimator_

Best estimate of parameters according to GridSearchCV:
MLPClassifier(activation='logistic', hidden_layer_sizes=3, max_fun=500,
              max_iter=200000, random_state=125, solver='lbfgs')


In [12]:
print("Best result of the cross validation of the model with the best paramters:" +str(clf.best_score_))

Best result of the cross validation of the model with the best paramters:0.41674876847290643


### 5. Prediction

In [13]:
# Making predictions with the optimal model on the training dataset
yhatTrain = model.predict(XTrain)
contTrain = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTrain),1) :
    if (yhatTrain[i] == yTrain[i]):
        contTrain = contTrain + 1

In [14]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(XTest)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTest),1) :
    if (yhatTest[i] == yTest[i]):
        contTest = contTest + 1


### 6. Results

In [15]:
print('Final accuracy on the training dataset:' + str(contTrain/len(yTrain)))
print('Final accuracy on the testing dataset: ' + str(contTest/len(yTest)))

Final accuracy on the training dataset:0.7152777777777778
Final accuracy on the testing dataset: 0.4864864864864865


In [16]:
from sklearn.metrics import classification_report,confusion_matrix

print('----------------Confusion Matrix (Training)------------------')
print(confusion_matrix(yTrain,yhatTrain))
print('Input data:  ' + str(np.array(yTrain)))
print('Prediction:        ' +str(yhatTrain))

----------------Confusion Matrix (Training)------------------
[[63  0  4]
 [14  4  7]
 [16  0 36]]
Input data:  [1 0 2 0 2 2 0 0 2 0 2 0 1 0 2 2 0 2 2 2 0 0 0 2 0 0 0 0 1 1 2 2 2 2 0 1 2
 0 0 2 1 2 2 1 0 0 2 2 1 0 0 0 2 0 0 2 0 2 1 2 0 2 1 0 0 0 0 2 2 2 0 2 0 0
 0 2 0 2 0 0 0 1 2 0 0 1 2 2 1 1 0 2 0 2 0 0 1 0 1 0 0 2 0 0 2 2 2 1 0 2 2
 1 2 0 1 0 0 0 2 0 1 0 2 0 0 2 1 1 0 0 0 2 0 1 0 0 0 2 2 2 1 2 0 1]
Prediction:        [1 0 0 0 0 2 0 0 0 0 2 2 0 0 2 2 0 0 2 2 0 0 0 2 0 0 0 0 1 0 0 2 2 2 0 0 2
 0 0 2 0 0 2 2 0 0 0 0 2 0 0 0 0 0 0 2 0 2 2 2 2 0 0 0 0 0 0 2 2 0 0 2 0 2
 0 0 0 2 0 0 0 2 2 0 0 0 0 0 2 2 0 2 0 2 0 0 1 0 0 2 0 0 0 0 0 2 2 0 0 2 2
 0 2 0 2 0 0 0 2 0 0 0 2 0 0 2 0 1 0 0 0 2 0 0 0 0 0 2 2 2 0 2 0 0]


In [17]:
print(classification_report(yTrain,yhatTrain))

              precision    recall  f1-score   support

           0       0.68      0.94      0.79        67
           1       1.00      0.16      0.28        25
           2       0.77      0.69      0.73        52

    accuracy                           0.72       144
   macro avg       0.81      0.60      0.60       144
weighted avg       0.77      0.72      0.68       144



In [18]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(yTest,yhatTest))
print('Input data:  ' + str(np.array(yTest)))
print('Prediction:        ' +str(yhatTest))

----------------Confusion Matrix (Test)------------------
[[13  1  4]
 [ 3  0  3]
 [ 8  0  5]]
Input data:  [0 1 0 2 0 2 1 0 1 0 2 2 1 2 2 0 1 2 0 0 0 2 1 0 0 2 0 2 2 0 0 0 2 2 0 0 0]
Prediction:        [0 0 0 0 0 0 2 0 0 0 0 0 2 0 2 0 0 2 0 0 0 0 2 0 2 2 2 0 2 2 0 1 0 2 0 0 2]


In [19]:
print(classification_report(yTest,yhatTest))

              precision    recall  f1-score   support

           0       0.54      0.72      0.62        18
           1       0.00      0.00      0.00         6
           2       0.42      0.38      0.40        13

    accuracy                           0.49        37
   macro avg       0.32      0.37      0.34        37
weighted avg       0.41      0.49      0.44        37

