# Classification model using Multilayer Perceptron

### 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

### 2. Upload Clinic data

In [2]:
path ='../../../../Data_preprocessing/Prediction PFS/RNA+Clinic joined/New/Clinical_data_and_RNA_15_Features_PFS.csv'
data = pd.read_csv(path)
data.head()

Unnamed: 0                                RNA_ID   Age  Sarc  Rhab  \
0           0  G138701_RCCBMS-00020-T_v1_RNA_OnPrem  62.0   0.0   0.0   
1           1  G138701_RCCBMS-00097-T_v1_RNA_OnPrem  67.0   0.0   0.0   
2           2  G138701_RCCBMS-00141-T_v1_RNA_OnPrem  62.0   0.0   0.0   
3           3  G138701_RCCBMS-00099-T_v1_RNA_OnPrem  60.0   0.0   0.0   
4           4  G138701_RCCBMS-00163-T_v1_RNA_OnPrem  76.0   0.0   0.0   

   Number_of_Prior_Therapies  \
0                        2.0   
1                        2.0   
2                        1.0   
3                        3.0   
4                        2.0   

   Days_from_TumorSample_Collection_and_Start_of_Trial_Therapy  \
0                                              962.0             
1                                              254.0             
2                                              800.0             
3                                              790.0             
4                                             1241.0             

   Tumor_Shrinkage        PFS  TM_TC_Ratio  ...      IL25  LANCL1-AS1  \
0       -16.406250  12.164384     0.766909  ...  21.08036    21.39991   
1       -40.000000   5.490411     0.773269  ...  21.08036    21.39991   
2       -89.436620  61.906849     1.782859  ...  21.08036    21.39991   
3        11.787072   1.249315     5.890573  ...  21.08036    21.39991   
4         0.000000   5.654795     1.374775  ...  21.08036    21.39991   

      LEMD1     PCMT1  RP11-120J4.1  RP11-374M1.2   SDR42E1    TARBP2  \
0  22.39503  31.44953       21.4144      21.24656  30.26124  29.60417   
1  22.39503  33.02746       21.4144      21.24656  29.12730  29.61188   
2  22.39503  33.75531       21.4144      21.24656  27.22907  31.90343   
3  29.70759  33.50304       21.4144      21.24656  22.83731  30.35424   
4  22.39503  33.18274       21.4144      21.24656  22.83731  31.60946   

   TRIM43B   VN2R17P  
0  21.9744  21.12857  
1  21.9744  21.12857  
2  21.9744  21.12857  
3  21.9744  21.12857  
4  21.9744  21.12857  

[5 rows x 42 columns]

In [3]:
Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    elif data.PFS[i]<6: # If PFS is over 6 months, I will consider it as Responder (R)
        Y.append(1)
    else:
        Y.append(2) # If PFS is between 3 and 6 months, I will consider it as SemiResponder (SR)
   

data = data.drop('PFS', axis=1)
data = data.drop('RNA_ID', axis=1)

X = data.iloc[:,1:42] 
# I selected all the columns by removing the Unnamed column (row id) and the Target column.
print(X)
print('Number of patients: ',len(Y))

      Age  Sarc  Rhab  Number_of_Prior_Therapies  \
0    62.0   0.0   0.0                        2.0   
1    67.0   0.0   0.0                        2.0   
2    62.0   0.0   0.0                        1.0   
3    60.0   0.0   0.0                        3.0   
4    76.0   0.0   0.0                        2.0   
..    ...   ...   ...                        ...   
176  77.0   0.0   0.0                        1.0   
177  54.0   0.0   0.0                        1.0   
178  64.0   0.0   0.0                        1.0   
179  75.0   0.0   0.0                        1.0   
180  50.0   0.0   0.0                        1.0   

     Days_from_TumorSample_Collection_and_Start_of_Trial_Therapy  \
0                                                962.0             
1                                                254.0             
2                                                800.0             
3                                                790.0             
4                                  

### 3. Train-Test dataset split

In [4]:
XTrain, XTest, yTrain, yTest = train_test_split(X, Y, test_size=0.20, random_state=125, stratify=Y)

print('Training set size:', len(XTrain))
print('Target column size of the training set:', len(yTrain))
print('Test set size:', len(XTest))
print('Target column size of the test set:', len(yTest))

Training set size: 144
Target column size of the training set: 144
Test set size: 37
Target column size of the test set: 37


In [5]:
param_grid = {'max_iter': [200000, 500000, 10000000],
            'activation': ['identity', 'logistic', 'tanh', 'relu'],
            'random_state': [125],
            'max_fun': [300, 500,1000, 5000, 10000, 15000, 20000],
            'hidden_layer_sizes': [3,5],
            'solver': ['lbfgs']}

# I created a GridSearchCV which allows us to systematically evaluate and select the parameters of our model.
# By indicating a model and the parameters to test, you can evaluate the performance of the first one based on the
# seconds through cross validation.
clf = GridSearchCV(MLPClassifier(), param_grid, cv =5)

clf.fit(XTrain , yTrain)


C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lb

GridSearchCV(cv=5, estimator=MLPClassifier(),
             param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'],
                         'hidden_layer_sizes': [3, 5],
                         'max_fun': [300, 500, 1000, 5000, 10000, 15000, 20000],
                         'max_iter': [200000, 500000, 10000000],
                         'random_state': [125], 'solver': ['lbfgs']})

In [6]:
print("Best estimate of parameters according to GridSearchCV:")
print(clf.best_estimator_)
# Fit the model with the best parameters
model = clf.best_estimator_

Best estimate of parameters according to GridSearchCV:
MLPClassifier(activation='identity', hidden_layer_sizes=5, max_fun=500,
              max_iter=200000, random_state=125, solver='lbfgs')


In [7]:
print("Best result of the cross validation of the model with the best paramters:" +str(clf.best_score_))

Best result of the cross validation of the model with the best paramters:0.687192118226601


### 5. Prediction

In [8]:
# Making predictions with the optimal model on the training dataset
yhatTrain = model.predict(XTrain)
contTrain = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTrain),1) :
    if (yhatTrain[i] == yTrain[i]):
        contTrain = contTrain + 1

In [9]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(XTest)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTest),1) :
    if (yhatTest[i] == yTest[i]):
        contTest = contTest + 1


### 6. Results

In [10]:
print('Final accuracy on the training dataset:' + str(contTrain/len(yTrain)))
print('Final accuracy on the testing dataset: ' + str(contTest/len(yTest)))

Final accuracy on the training dataset:0.6666666666666666
Final accuracy on the testing dataset: 0.7567567567567568


In [11]:
from sklearn.metrics import classification_report,confusion_matrix

print('----------------Confusion Matrix (Training)------------------')
print(confusion_matrix(yTrain,yhatTrain))
print('Input data:  ' + str(np.array(yTrain)))
print('Prediction:        ' +str(yhatTrain))

----------------Confusion Matrix (Training)------------------
[[56  3  8]
 [15  2  8]
 [11  3 38]]
Input data:  [1 0 2 0 2 2 0 0 2 0 2 0 1 0 2 2 0 2 2 2 0 0 0 2 0 0 0 0 1 1 2 2 2 2 0 1 2
 0 0 2 1 2 2 1 0 0 2 2 1 0 0 0 2 0 0 2 0 2 1 2 0 2 1 0 0 0 0 2 2 2 0 2 0 0
 0 2 0 2 0 0 0 1 2 0 0 1 2 2 1 1 0 2 0 2 0 0 1 0 1 0 0 2 0 0 2 2 2 1 0 2 2
 1 2 0 1 0 0 0 2 0 1 0 2 0 0 2 1 1 0 0 0 2 0 1 0 0 0 2 2 2 1 2 0 1]
Prediction:        [2 0 2 0 2 1 0 2 2 0 1 0 0 0 2 0 0 0 2 2 2 1 0 2 0 0 0 0 0 1 0 2 2 2 0 0 0
 0 0 0 0 2 2 0 0 0 2 2 0 0 2 0 2 0 2 2 0 0 2 2 0 0 2 0 0 2 2 2 2 2 0 2 0 0
 0 2 0 2 0 0 0 0 2 0 0 2 2 2 1 2 0 0 0 0 0 2 0 0 0 0 1 2 0 0 2 2 2 0 0 2 0
 0 2 0 0 0 0 0 2 0 2 0 2 0 0 0 0 2 0 0 2 2 0 0 0 0 0 1 2 2 2 2 1 0]


In [12]:
print(classification_report(yTrain,yhatTrain))

              precision    recall  f1-score   support

           0       0.68      0.84      0.75        67
           1       0.25      0.08      0.12        25
           2       0.70      0.73      0.72        52

    accuracy                           0.67       144
   macro avg       0.55      0.55      0.53       144
weighted avg       0.62      0.67      0.63       144



In [13]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(yTest,yhatTest))
print('Input data:  ' + str(np.array(yTest)))
print('Prediction:        ' +str(yhatTest))

----------------Confusion Matrix (Test)------------------
[[16  1  1]
 [ 3  1  2]
 [ 1  1 11]]
Input data:  [0 1 0 2 0 2 1 0 1 0 2 2 1 2 2 0 1 2 0 0 0 2 1 0 0 2 0 2 2 0 0 0 2 2 0 0 0]
Prediction:        [1 0 0 2 2 2 2 0 1 0 1 2 2 2 2 0 0 2 0 0 0 2 0 0 0 2 0 2 0 0 0 0 2 2 0 0 0]


In [14]:
print(classification_report(yTest,yhatTest))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84        18
           1       0.33      0.17      0.22         6
           2       0.79      0.85      0.81        13

    accuracy                           0.76        37
   macro avg       0.64      0.63      0.63        37
weighted avg       0.72      0.76      0.73        37



### Everolimus test

In [15]:
path ='../../../../Data_preprocessing/Testing with everolimus/RNA+Clinic joined/Clinical_data_and_RNA_15_Features_everolimus.csv'
data = pd.read_csv(path)

Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    else:
        Y.append(1)# If PFS is over 3 months, I will consider it as Responder (R)
data=data.drop([ 'PFS', 'RNA_ID', 'Unnamed: 0'], axis=1)

FileNotFoundError: [Errno 2] No such file or directory: '../../../../Data_preprocessing/Testing with everolimus/RNA+Clinic joined/Clinical_data_and_RNA_15_Features_everolimus.csv'

In [ ]:
data.head(5)

Age  Sarc  Rhab  Number_of_Prior_Therapies  \
0  63.0   0.0   0.0                        1.0   
1  63.0   0.0   0.0                        1.0   
2  63.0   0.0   0.0                        1.0   
3  63.0   0.0   0.0                        1.0   
4  63.0   0.0   0.0                        1.0   

   Days_from_TumorSample_Collection_and_Start_of_Trial_Therapy  \
0                                          727.50000             
1                                          724.75000             
2                                          723.37500             
3                                          722.68750             
4                                          723.03125             

   Tumor_Shrinkage  TM_TC_Ratio  Cohort_CM-009  Cohort_CM-010  Cohort_CM-025  \
0        -1.204819     1.410021            0.0            0.0              1   
1        -1.204819     1.410021            0.0            0.0              1   
2        -1.204819     1.410021            0.0            0.0              1   
3        -1.204819     1.410021            0.0            0.0              1   
4        -1.204819     1.410021            0.0            0.0              1   

   ...      IL25  LANCL1-AS1     LEMD1     PCMT1  RP11-120J4.1  RP11-374M1.2  \
0  ...  26.08443    20.80222  27.25909  31.88845      21.00147      20.88333   
1  ...  20.96655    21.00482  21.37538  32.63174      20.87745      20.97230   
2  ...  20.96655    21.00482  28.29412  32.02466      25.18146      20.97230   
3  ...  23.22419    21.00482  29.09650  31.79012      20.87745      23.45302   
4  ...  24.52277    21.00482  30.79227  32.62895      26.14020      20.97230   

    SDR42E1    TARBP2   TRIM43B   VN2R17P  
0  28.23012  31.08288  25.51490  20.93829  
1  27.55631  30.93771  23.29578  20.99449  
2  28.44482  32.20350  20.68433  20.99449  
3  30.92530  30.41685  23.83079  20.99449  
4  29.51644  31.69236  20.68433  20.99449  

[5 rows x 39 columns]

In [ ]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(data)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(Y),1) :
    if (yhatTest[i] == Y[i]):
        contTest = contTest + 1

print('Final accuracy on the testing dataset: ' + str(contTest/len(Y)))

Final accuracy on the testing dataset: 0.2923076923076923


C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\base.py:488: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names must be in the same order as they were in fit.

  warnings.warn(message, FutureWarning)


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y, yhatTest)
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix)
print('Input data:  ' + str(np.array(Y)))
print('Prediction:        ' +str(yhatTest))


print(classification_report(Y, yhatTest))

----------------Confusion Matrix (Test)------------------
[[14 23 23]
 [ 0 24 46]
 [ 0  0  0]]
Input data:  [1 1 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0
 1 0 1 0 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 1 1 0
 0 1 0 0 0 1 1 0 0 1 1 1 1 0 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 1
 0 1 0 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 0]
Prediction:        [1 2 2 0 0 2 1 2 0 2 2 1 2 2 2 2 1 2 1 0 2 0 2 1 1 2 1 1 1 2 2 1 0 1 1 1 0
 2 2 2 2 2 1 2 0 2 1 1 2 0 2 2 0 1 2 1 1 1 1 0 2 1 1 2 2 2 2 2 1 1 2 2 2 1
 2 2 2 2 0 2 2 1 2 1 2 2 2 1 1 2 1 1 2 2 2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 0 1
 2 1 1 2 2 2 1 2 1 2 2 2 1 1 2 1 2 1 0]
              precision    recall  f1-score   support

           0       1.00      0.23      0.38        60
           1       0.51      0.34      0.41        70
           2       0.00      0.00      0.00         0

    accuracy                           0.29       130
   macro avg       0.50      0.19      0.26       130
weighted avg     

C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarni