# Classification model using Decision Tree

### 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV

### 2. Upload Clinic data

In [2]:
path ='../../../../Data_preprocessing/Prediction PFS/RNA+Clinic joined/Clinical_data_and_RNA_30_Features_PFS.csv'
data = pd.read_csv(path)
data.head()

Unnamed: 0                                RNA_ID   Age  Sarc  Rhab  \
0           0  G138701_RCCBMS-00020-T_v1_RNA_OnPrem  62.0   0.0   0.0   
1           1  G138701_RCCBMS-00097-T_v1_RNA_OnPrem  62.0   0.0   0.0   
2           2  G138701_RCCBMS-00141-T_v1_RNA_OnPrem  62.0   0.0   0.0   
3           3  G138701_RCCBMS-00099-T_v1_RNA_OnPrem  62.0   0.0   0.0   
4           4  G138701_RCCBMS-00163-T_v1_RNA_OnPrem  62.0   0.0   0.0   

   Number_of_Prior_Therapies  \
0                        2.0   
1                        2.0   
2                        1.0   
3                        3.0   
4                        2.0   

   Days_from_TumorSample_Collection_and_Start_of_Trial_Therapy  \
0                                              707.0             
1                                              707.0             
2                                              707.0             
3                                              707.0             
4                                              707.0             

   Tumor_Shrinkage        PFS  TM_TC_Ratio  ...  RP11-96O20.4  RP5-827C21.1  \
0              0.0  12.164384     1.374775  ...      21.18753      27.40814   
1              0.0   5.490411     1.374775  ...      21.18753      29.25015   
2              0.0  61.906849     1.374775  ...      21.18753      23.03429   
3              0.0   1.249315     1.374775  ...      21.18753      23.03429   
4              0.0   5.654795     1.374775  ...      21.18753      23.03429   

   RPS12P26   SDR42E1  SNORD113-5    TARBP2    TRAV41  TRIM43B   VN2R17P  \
0  31.71139  30.26124    21.32743  29.60417  22.22154  21.9744  21.12857   
1  29.15373  29.12730    21.32743  29.61188  22.22154  21.9744  21.12857   
2  29.37858  27.22907    21.32743  31.90343  22.22154  21.9744  21.12857   
3  30.19136  22.83731    21.32743  30.35424  22.22154  21.9744  21.12857   
4  31.82172  22.83731    21.32743  31.60946  22.22154  21.9744  21.12857   

        XPC  
0  32.24472  
1  32.15619  
2  31.86536  
3  31.63561  
4  33.12717  

[5 rows x 57 columns]

In [3]:
data = data[['RNA_ID','MSKCC_FAVORABLE', 'MSKCC_INTERMEDIATE', 'MSKCC_NA', 'MSKCC_POOR','PFS','AC005307.1', 'ATP5G2P1', 'DLGAP4', 'EIF4A1P9', 'FAM172BP', 'FAM224A', 'GJA9', 'GPR155', 'GYPE', 'IL25', 'KLHL5', 'LANCL1-AS1', 'LEMD1', 'PCMT1', 'RP11-120J4.1', 'RP11-20G6.3', 'RP11-349G13.2', 'RP11-374M1.2', 'RP11-536C10.21', 'RP11-95G17.2', 'RP11-96O20.4', 'RP5-827C21.1', 'RPS12P26', 'SDR42E1', 'SNORD113-5', 'TARBP2', 'TRAV41', 'TRIM43B', 'VN2R17P', 'XPC']]
data.head()

RNA_ID  MSKCC_FAVORABLE  MSKCC_INTERMEDIATE  \
0  G138701_RCCBMS-00020-T_v1_RNA_OnPrem                1                   0   
1  G138701_RCCBMS-00097-T_v1_RNA_OnPrem                1                   0   
2  G138701_RCCBMS-00141-T_v1_RNA_OnPrem                0                   0   
3  G138701_RCCBMS-00099-T_v1_RNA_OnPrem                1                   0   
4  G138701_RCCBMS-00163-T_v1_RNA_OnPrem                0                   1   

   MSKCC_NA  MSKCC_POOR        PFS  AC005307.1   ATP5G2P1    DLGAP4  EIF4A1P9  \
0         0           0  12.164384   21.055379  21.300337  34.54982  21.37925   
1         0           0   5.490411   21.055379  21.300337  34.06647  21.37925   
2         0           1  61.906849   21.055379  21.300337  34.42561  25.08766   
3         0           0   1.249315   21.055379  21.300337  34.41176  26.76156   
4         0           0   5.654795   21.055379  21.300337  34.29088  21.37925   

   ...  RP11-96O20.4  RP5-827C21.1  RPS12P26   SDR42E1  SNORD113-5    TARBP2  \
0  ...      21.18753      27.40814  31.71139  30.26124    21.32743  29.60417   
1  ...      21.18753      29.25015  29.15373  29.12730    21.32743  29.61188   
2  ...      21.18753      23.03429  29.37858  27.22907    21.32743  31.90343   
3  ...      21.18753      23.03429  30.19136  22.83731    21.32743  30.35424   
4  ...      21.18753      23.03429  31.82172  22.83731    21.32743  31.60946   

     TRAV41  TRIM43B   VN2R17P       XPC  
0  22.22154  21.9744  21.12857  32.24472  
1  22.22154  21.9744  21.12857  32.15619  
2  22.22154  21.9744  21.12857  31.86536  
3  22.22154  21.9744  21.12857  31.63561  
4  22.22154  21.9744  21.12857  33.12717  

[5 rows x 36 columns]

In [4]:
Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    elif data.PFS[i]<6: # If PFS is over 6 months, I will consider it as Responder (R)
        Y.append(1)
    else:
        Y.append(2) # If PFS is between 3 and 6 months, I will consider it as SemiResponder (SR)
        

# As I won't need this columns any more, I deleted them.
data = data.drop('PFS', axis=1)
data = data.drop('RNA_ID', axis=1)

X = data.iloc[:,0:36] # I selected all the columns by removing the Unnamed column (row id) and the Target column.

print(X)
print('Numero de pacientes: ',len(Y))

     MSKCC_FAVORABLE  MSKCC_INTERMEDIATE  MSKCC_NA  MSKCC_POOR  AC005307.1  \
0                  1                   0         0           0   21.055379   
1                  1                   0         0           0   21.055379   
2                  0                   0         0           1   21.055379   
3                  1                   0         0           0   21.055379   
4                  0                   1         0           0   21.055379   
..               ...                 ...       ...         ...         ...   
176                0                   0         1           0   20.944668   
177                0                   0         1           0   20.944668   
178                0                   0         1           0   20.944668   
179                0                   0         1           0   20.944668   
180                0                   0         1           0   20.944668   

      ATP5G2P1    DLGAP4  EIF4A1P9  FAM172BP   FAM224A  ...  RP

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=125)


print('Training set size:', len(X_train))
print('Target column size of the training set:', len(y_train))
print('Test set size:', len(X_test))
print('Target column size of the test set:', len(y_test))

Training set size: 144
Target column size of the training set: 144
Test set size: 37
Target column size of the test set: 37


### 4. Select the parameters of the model and fit it

In [6]:
param_grid = {'C': [1,2,5,7,10],
            'solver': ['newton-cg','liblinear'],  
            'max_iter':[20000,50000,100000],
            'random_state':[125]}

# Creamos un GridSearchCV que permite evaluar y seleccionar de forma sistemática los parámetros de nuestro modelo. 
# Indicándole un modelo y los parámetros a probar, puede evaluar el rendimiento del primero en función de los 
# segundos mediante validación cruzada.  
clf = GridSearchCV(LogisticRegression(), param_grid, cv = 5)
clf.fit(X_train , y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 5, 7, 10],
                         'max_iter': [20000, 50000, 100000],
                         'random_state': [125],
                         'solver': ['newton-cg', 'liblinear']})

In [7]:
print("Best estimate of parameters according to GridSearchCV:")
model = clf.best_estimator_
# Fit the model with the best parameters
model.fit(X_train , y_train)

Best estimate of parameters according to GridSearchCV:


LogisticRegression(C=10, max_iter=20000, random_state=125, solver='liblinear')

In [8]:
print("Best result of the cross validation of the model with the best paramters:" +str(clf.best_score_))

Best result of the cross validation of the model with the best paramters:0.6958128078817734


In [9]:
# Making predictions with the optimal model on the training dataset
yhatTrain = model.predict(X_train)
contTrain = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(y_train),1) :
    if (yhatTrain[i] == y_train[i]):
        contTrain = contTrain + 1

In [10]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(X_test)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(y_test),1) :
    if (yhatTest[i] == y_test[i]):
        contTest = contTest + 1

In [11]:
print('Final accuracy on the training dataset:' + str(contTrain/len(y_train)))
print('Final accuracy on the testing dataset: ' + str(contTest/len(y_test)))

Final accuracy on the training dataset:0.875
Final accuracy on the testing dataset: 0.7027027027027027


In [12]:
from sklearn.metrics import classification_report,confusion_matrix

print('----------------Confusion Matrix (Training)------------------')
print(confusion_matrix(y_train,yhatTrain))
print('Input data:  ' + str(np.array(y_train)))
print('Prediction:        ' +str(yhatTrain))

----------------Confusion Matrix (Training)------------------
[[65  0  0]
 [ 1 16 11]
 [ 1  5 45]]
Input data:  [0 2 1 1 1 1 0 2 0 1 2 2 1 0 2 0 2 0 0 0 2 1 0 0 2 2 0 1 0 0 1 1 0 2 1 0 1
 2 0 2 2 0 0 1 0 1 1 0 1 0 0 1 0 0 0 2 0 2 0 2 1 0 2 2 0 2 2 2 0 2 0 2 0 2
 2 0 0 2 0 0 1 2 1 0 0 0 0 2 1 2 2 0 0 2 2 2 2 0 0 0 2 0 2 0 0 0 0 1 0 2 0
 2 0 2 1 0 0 0 0 1 2 2 0 2 0 2 2 0 1 2 0 1 2 0 0 2 2 1 2 1 2 2 0 0]
Prediction:        [0 2 1 0 1 2 0 2 0 2 2 2 1 0 1 0 2 0 0 0 2 2 0 0 1 2 0 1 0 0 1 2 0 2 1 0 1
 2 0 2 2 0 0 1 0 1 1 0 2 0 0 2 0 0 0 2 0 2 0 2 2 0 2 2 0 2 2 2 0 2 0 0 0 2
 2 0 0 2 0 0 2 2 2 0 0 0 0 2 1 2 2 0 0 1 2 1 2 0 0 0 2 0 2 0 0 0 0 1 0 2 0
 2 0 2 1 0 0 0 0 2 2 1 0 2 0 2 2 0 1 2 0 2 2 0 0 2 2 1 2 1 2 2 0 0]


In [13]:
print(classification_report(y_train,yhatTrain))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98        65
           1       0.76      0.57      0.65        28
           2       0.80      0.88      0.84        51

    accuracy                           0.88       144
   macro avg       0.85      0.82      0.83       144
weighted avg       0.87      0.88      0.87       144



In [14]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(y_test,yhatTest))
print('Input data:  ' + str(np.array(y_test)))
print('Prediction:        ' +str(yhatTest))

----------------Confusion Matrix (Test)------------------
[[16  3  1]
 [ 0  3  0]
 [ 4  3  7]]
Input data:  [1 0 0 2 2 1 0 2 2 2 0 0 0 0 0 0 2 0 1 0 0 0 0 2 0 0 2 2 2 0 0 2 0 0 2 2 2]
Prediction:        [1 0 0 0 2 1 0 2 2 2 0 0 0 2 0 0 0 0 1 0 0 1 1 0 0 0 0 1 2 0 0 2 1 0 2 1 1]


In [15]:
print(classification_report(y_test, yhatTest))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80        20
           1       0.33      1.00      0.50         3
           2       0.88      0.50      0.64        14

    accuracy                           0.70        37
   macro avg       0.67      0.77      0.65        37
weighted avg       0.79      0.70      0.71        37



*Everolimus test*

In [16]:
path ='../../../../Data_preprocessing/Testing with everolimus/RNA+Clinic joined/Clinical_data_and_RNA_30_Features_everolimus.csv'
data = pd.read_csv(path)
data = data[['RNA_ID','MSKCC_FAVORABLE', 'MSKCC_INTERMEDIATE', 'MSKCC_NA', 'MSKCC_POOR','PFS','AC005307.1', 'ATP5G2P1', 'DLGAP4', 'EIF4A1P9', 'FAM172BP', 'FAM224A', 'GJA9', 'GPR155', 'GYPE', 'IL25', 'KLHL5', 'LANCL1-AS1', 'LEMD1', 'PCMT1', 'RP11-120J4.1', 'RP11-20G6.3', 'RP11-349G13.2', 'RP11-374M1.2', 'RP11-536C10.21', 'RP11-95G17.2', 'RP11-96O20.4', 'RP5-827C21.1', 'RPS12P26', 'SDR42E1', 'SNORD113-5', 'TARBP2', 'TRAV41', 'TRIM43B', 'VN2R17P', 'XPC']]

Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    elif data.PFS[i]<6:
        Y.append(1)
    else:
        Y.append(2)# If PFS is over 3 months, I will consider it as Responder (R)
data=data.drop([ 'PFS', 'RNA_ID'], axis=1)

In [17]:
data.head(5)

MSKCC_FAVORABLE  MSKCC_INTERMEDIATE  MSKCC_NA  MSKCC_POOR  AC005307.1  \
0                1                   0       0.0           0   20.963165   
1                1                   0       0.0           0   21.013460   
2                0                   1       0.0           0   21.013460   
3                0                   0       0.0           1   21.013460   
4                1                   0       0.0           0   21.013460   

    ATP5G2P1    DLGAP4  EIF4A1P9  FAM172BP   FAM224A  ...  RP11-96O20.4  \
0  20.718850  34.41635  23.50908  24.03405  20.93744  ...      20.77248   
1  21.007349  34.33893  21.04557  21.20204  20.99973  ...      21.03524   
2  27.386479  34.45158  26.25294  21.20204  20.99973  ...      21.03524   
3  21.007349  34.07963  21.04557  25.10356  20.99973  ...      21.03524   
4  21.007349  33.36643  23.43899  21.20204  20.99973  ...      21.03524   

   RP5-827C21.1  RPS12P26   SDR42E1  SNORD113-5    TARBP2    TRAV41   TRIM43B  \
0      27.09131  31.45042  28.23012    21.27932  31.08288  25.86902  25.51490   
1      26.79393  28.60666  27.55631    20.88605  30.93771  29.24738  23.29578   
2      25.96827  29.55728  28.44482    20.88605  32.20350  30.68048  20.68433   
3      26.26191  28.32744  30.92530    20.88605  30.41685  29.69705  23.83079   
4      25.45149  29.25251  29.51644    20.88605  31.69236  21.47750  20.68433   

    VN2R17P       XPC  
0  20.93829  31.96084  
1  20.99449  32.62522  
2  20.99449  32.66731  
3  20.99449  32.59007  
4  20.99449  32.31981  

[5 rows x 34 columns]

In [18]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(data)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(Y),1) :
    if (yhatTest[i] == Y[i]):
        contTest = contTest + 1

print('Final accuracy on the testing dataset: ' + str(contTest/len(Y)))

Final accuracy on the testing dataset: 0.6692307692307692


In [19]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(Y,yhatTest))
print('Input data:  ' + str(np.array(Y)))
print('Prediction:        ' +str(yhatTest))
print(classification_report(Y,yhatTest))

----------------Confusion Matrix (Test)------------------
[[54  1  5]
 [ 4  6 17]
 [ 5 11 27]]
Input data:  [2 2 0 0 0 1 2 1 0 0 1 2 2 1 1 1 2 1 0 0 2 0 0 1 2 2 0 1 2 0 0 0 0 2 2 0 0
 2 0 2 0 2 2 0 0 0 1 0 1 0 1 1 0 2 0 0 0 0 2 0 0 0 0 1 1 2 1 1 0 0 2 2 1 0
 0 2 0 0 0 2 2 0 0 2 1 2 2 0 0 2 0 2 1 0 2 1 2 1 2 0 0 1 2 2 2 2 1 0 0 0 2
 0 1 0 2 0 0 2 2 1 1 2 0 2 0 2 0 0 0 0]
Prediction:        [1 2 0 0 0 2 2 2 0 0 2 1 2 1 2 2 0 0 0 0 2 0 2 1 0 2 0 0 2 2 0 0 0 0 1 0 0
 1 0 2 0 2 1 0 0 0 1 1 2 0 2 2 0 1 0 0 0 0 1 0 0 0 0 2 2 2 2 0 0 0 2 2 2 0
 0 2 0 0 0 2 2 0 0 0 2 1 2 0 0 2 0 1 2 0 2 2 2 1 2 0 0 2 2 2 2 2 1 0 2 0 1
 0 1 0 1 2 0 2 2 0 2 2 0 0 0 2 2 0 0 0]
              precision    recall  f1-score   support

           0       0.86      0.90      0.88        60
           1       0.33      0.22      0.27        27
           2       0.55      0.63      0.59        43

    accuracy                           0.67       130
   macro avg       0.58      0.58      0.58       130
weighted avg     