# Classification model using Decision Tree

### 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV

### 2. Upload RNA data

In [2]:
path ='../../../Data_preprocessing/Prediction PFS/RNA+Clinic joined/Clinical_data_and_RNA_total_Features_PFS.csv'
data = pd.read_csv(path)
data.head(5)

Unnamed: 0                                RNA_ID   Age  Sarc  Rhab  \
0           0  G138701_RCCBMS-00020-T_v1_RNA_OnPrem  62.0   0.0   0.0   
1           1  G138701_RCCBMS-00097-T_v1_RNA_OnPrem  62.0   0.0   0.0   
2           2  G138701_RCCBMS-00141-T_v1_RNA_OnPrem  62.0   0.0   0.0   
3           3  G138701_RCCBMS-00099-T_v1_RNA_OnPrem  62.0   0.0   0.0   
4           4  G138701_RCCBMS-00163-T_v1_RNA_OnPrem  62.0   0.0   0.0   

   Number_of_Prior_Therapies  \
0                        2.0   
1                        2.0   
2                        1.0   
3                        3.0   
4                        2.0   

   Days_from_TumorSample_Collection_and_Start_of_Trial_Therapy  \
0                                              707.0             
1                                              707.0             
2                                              707.0             
3                                              707.0             
4                                              707.0             

   Tumor_Shrinkage        PFS  TM_TC_Ratio  ...    ZWILCH     ZWINT      ZXDA  \
0              0.0  12.164384     1.374775  ...  33.26816  30.04056  30.36292   
1              0.0   5.490411     1.374775  ...  31.53633  29.94062  30.80829   
2              0.0  61.906849     1.374775  ...  30.74474  31.95812  30.73898   
3              0.0   1.249315     1.374775  ...  31.63196  30.71732  31.09654   
4              0.0   5.654795     1.374775  ...  31.75620  30.75149  30.55896   

       ZXDB      ZXDC    ZYG11A    ZYG11B       ZYX     ZZEF1      ZZZ3  
0  30.98129  32.38442  28.01561  31.24379  33.81903  33.22469  31.23383  
1  30.74475  32.09470  26.32526  32.70057  33.67262  33.10198  32.44643  
2  30.15898  31.69473  26.33098  32.68330  33.96047  32.97135  32.20607  
3  30.25757  31.90774  27.53819  32.64194  34.54254  33.24885  32.78278  
4  30.17101  31.01545  21.45312  32.86620  34.24375  34.86720  32.73361  

[5 rows x 43921 columns]

In [3]:
X = data.iloc[:,28:43921  ] 
Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    elif data.PFS[i]<6:
        Y.append(1)
    else:
        Y.append(2)# If PFS is over 3 months, I will consider it as Responder (R)

X

5S_rRNA        7SK       A1BG   A1BG-AS1       A1CF        A2M  \
0    21.038652  35.199603  30.187983  22.999432  33.643965  37.130851   
1    21.038652  38.183943  30.483638  25.581769  28.866645  37.945043   
2    21.038652  37.141292  30.092851  26.933385  26.684228  36.851946   
3    21.038652  36.447015  30.975010  26.683128  32.521495  38.453517   
4    21.038652  37.623923  26.915750  22.999432  23.219176  38.931987   
..         ...        ...        ...        ...        ...        ...   
176  21.038043  36.338729  30.954407  27.310879  26.161567  38.376185   
177  21.038043  38.248915  33.110149  26.793199  26.161567  36.537388   
178  21.038043  35.884812  32.880283  25.659842  31.822942  38.265866   
179  21.038043  35.283776  30.658715  27.533890  32.930512  36.882090   
180  21.038043  36.694546  27.118678  17.788726  33.128697  35.626724   

       A2M-AS1      A2ML1  A2ML1-AS1      A2MP1  ...    ZWILCH     ZWINT  \
0    22.705126  22.869853  21.076515  21.271282  ...  33.26816  30.04056   
1    27.797609  24.142100  21.076515  21.271282  ...  31.53633  29.94062   
2    22.705126  30.406352  21.076515  21.271282  ...  30.74474  31.95812   
3    26.337846  28.229357  21.076515  21.271282  ...  31.63196  30.71732   
4    22.705126  22.869853  21.076515  21.271282  ...  31.75620  30.75149   
..         ...        ...        ...        ...  ...       ...       ...   
176  25.971821  24.438322  21.076088  21.056491  ...  31.62442  30.78532   
177  26.388265  24.438322  21.076088  21.056491  ...  31.40147  31.50200   
178  26.504307  24.438322  21.076088  21.056491  ...  31.21094  30.91066   
179  26.303147  24.438322  21.076088  21.056491  ...  31.12324  28.76312   
180  20.654847  24.438322  21.076088  21.056491  ...  32.79170  33.26885   

         ZXDA      ZXDB      ZXDC    ZYG11A    ZYG11B       ZYX     ZZEF1  \
0    30.36292  30.98129  32.38442  28.01561  31.24379  33.81903  33.22469   
1    30.80829  30.74475  32.09470  26.32526  32.70057  33.67262  33.10198   
2    30.73898  30.15898  31.69473  26.33098  32.68330  33.96047  32.97135   
3    31.09654  30.25757  31.90774  27.53819  32.64194  34.54254  33.24885   
4    30.55896  30.17101  31.01545  21.45312  32.86620  34.24375  34.86720   
..        ...       ...       ...       ...       ...       ...       ...   
176  30.86517  30.92600  31.53239  23.65585  32.42073  34.41045  33.21697   
177  29.96535  30.21446  31.49627  28.04168  32.19568  32.69615  32.18970   
178  31.35764  30.99788  31.45772  23.65585  32.36832  35.02409  34.26388   
179  31.48891  30.27351  32.88316  23.65585  31.76924  34.07224  34.35116   
180  31.30271  30.72641  31.65005  23.65585  30.82798  34.72915  33.65903   

         ZZZ3  
0    31.23383  
1    32.44643  
2    32.20607  
3    32.78278  
4    32.73361  
..        ...  
176  32.22166  
177  32.59554  
178  32.82148  
179  31.98965  
180  32.91379  

[181 rows x 43893 columns]

### 3. Train-Test dataset split

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=125)

print('Training set size:', len(X_train))
print('Target column size of the training set:', len(y_train))
print('Test set size:', len(X_test))
print('Target column size of the test set:', len(y_test))

Training set size: 144
Target column size of the training set: 144
Test set size: 37
Target column size of the test set: 37


### 4. Select the parameters of the model and fit it

In [5]:
param_grid = {'C': [1,2,5,7,10],
            'solver': ['newton-cg','liblinear'], # No escogemos ‘lbfgs’, ‘sag’ ni ‘saga’ porque no termina de 
                                                 # ejecutarse debido a: "TOTAL NO. of ITERATIONS REACHED LIMIT"
            'max_iter':[25,50,100,200,500,1000],
            'random_state':[125]}
# I created a GridSearchCV which allows us to systematically evaluate and select the parameters of our model.
# By indicating a model and the parameters to test, you can evaluate the performance of the first one based on the
# seconds through cross validation.
clf = GridSearchCV(LogisticRegression(), param_grid, cv = 5)
clf.fit(X_train , y_train)

C:\Users\sandr\anaconda3\lib\site-packages\sklearn\utils\optimize.py:202: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  warnings.warn("newton-cg failed to converge. Increase the "
C:\Users\sandr\anaconda3\lib\site-packages\sklearn\utils\optimize.py:202: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  warnings.warn("newton-cg failed to converge. Increase the "
C:\Users\sandr\anaconda3\lib\site-packages\sklearn\utils\optimize.py:202: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  warnings.warn("newton-cg failed to converge. Increase the "
C:\Users\sandr\anaconda3\lib\site-packages\sklearn\utils\optimize.py:202: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  warnings.warn("newton-cg failed to converge. Increase the "
C:\Users\sandr\anaconda3\lib\site-packages\sklearn\utils\optimize.py:202: ConvergenceWarning: newton-cg failed to co

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 5, 7, 10],
                         'max_iter': [25, 50, 100, 200, 500, 1000],
                         'random_state': [125],
                         'solver': ['newton-cg', 'liblinear']})

In [6]:
print("Best estimate of parameters according to GridSearchCV:")
model = clf.best_estimator_
# Fit the model with the best parameters
model.fit(X_train , y_train)

Best estimate of parameters according to GridSearchCV:


LogisticRegression(C=1, max_iter=25, random_state=125, solver='liblinear')

In [7]:
print("Best result of the cross validation of the model with the best paramters:" +str(clf.best_score_))

Best result of the cross validation of the model with the best paramters:0.4024630541871921


### 5. Prediction

In [8]:
# Making predictions with the optimal model on the training dataset
yhatTrain = model.predict(X_train)
contTrain = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(y_train),1) :
    if (yhatTrain[i] == y_train[i]):
        contTrain = contTrain + 1

In [9]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(X_test)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(y_test),1) :
    if (yhatTest[i] == y_test[i]):
        contTest = contTest + 1

In [10]:
print('Final accuracy on the training dataset:' + str(contTrain/len(y_train)))
print('Final accuracy on the testing dataset: ' + str(contTest/len(y_test)))

Final accuracy on the training dataset:1.0
Final accuracy on the testing dataset: 0.43243243243243246


In [11]:
from sklearn.metrics import classification_report,confusion_matrix

print('----------------Confusion Matrix (Training)------------------')
print(confusion_matrix(y_train,yhatTrain))
print('Input data:  ' + str(np.array(y_train)))
print('Prediction:        ' +str(yhatTrain))

----------------Confusion Matrix (Training)------------------
[[65  0  0]
 [ 0 28  0]
 [ 0  0 51]]
Input data:  [0 2 1 1 1 1 0 2 0 1 2 2 1 0 2 0 2 0 0 0 2 1 0 0 2 2 0 1 0 0 1 1 0 2 1 0 1
 2 0 2 2 0 0 1 0 1 1 0 1 0 0 1 0 0 0 2 0 2 0 2 1 0 2 2 0 2 2 2 0 2 0 2 0 2
 2 0 0 2 0 0 1 2 1 0 0 0 0 2 1 2 2 0 0 2 2 2 2 0 0 0 2 0 2 0 0 0 0 1 0 2 0
 2 0 2 1 0 0 0 0 1 2 2 0 2 0 2 2 0 1 2 0 1 2 0 0 2 2 1 2 1 2 2 0 0]
Prediction:        [0 2 1 1 1 1 0 2 0 1 2 2 1 0 2 0 2 0 0 0 2 1 0 0 2 2 0 1 0 0 1 1 0 2 1 0 1
 2 0 2 2 0 0 1 0 1 1 0 1 0 0 1 0 0 0 2 0 2 0 2 1 0 2 2 0 2 2 2 0 2 0 2 0 2
 2 0 0 2 0 0 1 2 1 0 0 0 0 2 1 2 2 0 0 2 2 2 2 0 0 0 2 0 2 0 0 0 0 1 0 2 0
 2 0 2 1 0 0 0 0 1 2 2 0 2 0 2 2 0 1 2 0 1 2 0 0 2 2 1 2 1 2 2 0 0]


In [12]:
print(classification_report(y_train,yhatTrain))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        65
           1       1.00      1.00      1.00        28
           2       1.00      1.00      1.00        51

    accuracy                           1.00       144
   macro avg       1.00      1.00      1.00       144
weighted avg       1.00      1.00      1.00       144



In [13]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(y_test,yhatTest))
print('Input data:  ' + str(np.array(y_test)))
print('Prediction:        ' +str(yhatTest))

----------------Confusion Matrix (Test)------------------
[[12  1  7]
 [ 2  0  1]
 [10  0  4]]
Input data:  [1 0 0 2 2 1 0 2 2 2 0 0 0 0 0 0 2 0 1 0 0 0 0 2 0 0 2 2 2 0 0 2 0 0 2 2 2]
Prediction:        [2 0 2 0 0 0 2 2 0 0 0 0 2 0 2 0 2 2 0 0 0 1 0 0 0 0 0 0 0 0 2 0 0 2 2 2 0]


In [14]:
print(classification_report(y_test, yhatTest))

              precision    recall  f1-score   support

           0       0.50      0.60      0.55        20
           1       0.00      0.00      0.00         3
           2       0.33      0.29      0.31        14

    accuracy                           0.43        37
   macro avg       0.28      0.30      0.28        37
weighted avg       0.40      0.43      0.41        37



*Everolimus test*

In [18]:
path ='../../../Data_preprocessing/Testing with everolimus/RNA+Clinic joined/Clinical_data_and_RNA_total_Features_everolimus.csv'
data = pd.read_csv(path)

Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    elif data.PFS[i]<6:
        Y.append(1)
    else:
        Y.append(2)# If PFS is over 3 months, I will consider it as Responder (R)
data = data.iloc[:,28:43921  ] 


In [19]:
data.head(5)

5S_rRNA        7SK       A1BG   A1BG-AS1       A1CF        A2M  \
0  21.026286  36.652074  29.917026  25.785487  32.336649  37.893923   
1  20.980824  36.069509  30.659901  24.752320  32.150625  37.917120   
2  20.980824  34.534739  32.518475  21.286965  31.316714  37.459082   
3  20.980824  35.985695  31.351233  27.411535  26.061145  38.521637   
4  20.980824  36.018506  31.793886  26.570343  32.083226  38.529937   

     A2M-AS1      A2ML1  A2ML1-AS1      A2MP1  ...    ZWILCH     ZWINT  \
0  25.809849  25.097570  20.976688  22.789947  ...  29.80793  29.85783   
1  24.924598  26.667438  20.980667  20.992693  ...  30.94629  29.83688   
2  24.981725  26.527944  20.980667  20.992693  ...  30.30043  29.50817   
3  26.727525  26.061061  20.980667  20.992693  ...  31.93313  30.76342   
4  25.580881  27.068514  20.980667  20.992693  ...  30.62509  30.50323   

       ZXDA      ZXDB      ZXDC    ZYG11A    ZYG11B       ZYX     ZZEF1  \
0  29.74131  30.14999  31.48907  23.23639  32.04080  34.20595  33.86610   
1  31.08671  30.90539  31.98263  28.35563  32.88150  33.76607  33.24248   
2  31.31077  30.39795  31.75137  23.88903  32.16635  34.09911  33.44950   
3  30.89048  30.56766  31.87580  25.83631  32.62290  34.47726  33.62134   
4  30.70842  30.07652  31.57023  28.19172  32.39844  34.24331  33.32216   

       ZZZ3  
0  32.05928  
1  32.57853  
2  31.38179  
3  32.80439  
4  31.97164  

[5 rows x 43893 columns]

In [20]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(data)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(Y),1) :
    if (yhatTest[i] == Y[i]):
        contTest = contTest + 1

print('Final accuracy on the testing dataset: ' + str(contTest/len(Y)))

Final accuracy on the testing dataset: 0.4846153846153846


In [21]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(Y,yhatTest))
print('Input data:  ' + str(np.array(Y)))
print('Prediction:        ' +str(yhatTest))
print(classification_report(Y,yhatTest))

----------------Confusion Matrix (Test)------------------
[[43  0 17]
 [18  0  9]
 [23  0 20]]
Input data:  [2 2 0 0 0 1 2 1 0 0 1 2 2 1 1 1 2 1 0 0 2 0 0 1 2 2 0 1 2 0 0 0 0 2 2 0 0
 2 0 2 0 2 2 0 0 0 1 0 1 0 1 1 0 2 0 0 0 0 2 0 0 0 0 1 1 2 1 1 0 0 2 2 1 0
 0 2 0 0 0 2 2 0 0 2 1 2 2 0 0 2 0 2 1 0 2 1 2 1 2 0 0 1 2 2 2 2 1 0 0 0 2
 0 1 0 2 0 0 2 2 1 1 2 0 2 0 2 0 0 0 0]
Prediction:        [0 0 2 2 2 0 0 2 0 0 0 0 0 2 0 2 0 0 0 0 2 0 2 0 0 0 0 0 0 2 2 0 0 2 2 0 0
 2 0 2 0 0 2 2 2 0 0 0 2 0 0 0 0 0 0 2 0 0 0 0 0 2 0 2 0 0 2 2 0 0 2 2 2 0
 0 2 0 0 0 2 0 0 0 2 0 0 0 2 2 0 2 0 0 0 2 0 2 2 2 0 0 0 2 2 2 0 0 2 0 0 2
 0 0 0 2 0 2 0 2 0 0 0 2 0 0 0 0 2 0 0]
              precision    recall  f1-score   support

           0       0.51      0.72      0.60        60
           1       0.00      0.00      0.00        27
           2       0.43      0.47      0.45        43

    accuracy                           0.48       130
   macro avg       0.32      0.39      0.35       130
weighted avg     

C:\Users\sandr\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sandr\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sandr\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
