# Classification model using Multilayer Perceptron

### 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

### 2. Upload RNA data

In [2]:
path ='../../../Data_preprocessing/Prediction PFS/RNA+Clinic joined/New/Clinical_data_and_RNA_total_Features_PFS.csv'
data = pd.read_csv(path)
data.head(5)

Unnamed: 0                                RNA_ID   Age  Sarc  Rhab  \
0           0  G138701_RCCBMS-00020-T_v1_RNA_OnPrem  62.0   0.0   0.0   
1           1  G138701_RCCBMS-00097-T_v1_RNA_OnPrem  67.0   0.0   0.0   
2           2  G138701_RCCBMS-00141-T_v1_RNA_OnPrem  62.0   0.0   0.0   
3           3  G138701_RCCBMS-00099-T_v1_RNA_OnPrem  60.0   0.0   0.0   
4           4  G138701_RCCBMS-00163-T_v1_RNA_OnPrem  76.0   0.0   0.0   

   Number_of_Prior_Therapies  \
0                        2.0   
1                        2.0   
2                        1.0   
3                        3.0   
4                        2.0   

   Days_from_TumorSample_Collection_and_Start_of_Trial_Therapy  \
0                                              962.0             
1                                              254.0             
2                                              800.0             
3                                              790.0             
4                                             1241.0             

   Tumor_Shrinkage        PFS  TM_TC_Ratio  ...    ZWILCH     ZWINT      ZXDA  \
0       -16.406250  12.164384     0.766909  ...  33.26816  30.04056  30.36292   
1       -40.000000   5.490411     0.773269  ...  31.53633  29.94062  30.80829   
2       -89.436620  61.906849     1.782859  ...  30.74474  31.95812  30.73898   
3        11.787072   1.249315     5.890573  ...  31.63196  30.71732  31.09654   
4         0.000000   5.654795     1.374775  ...  31.75620  30.75149  30.55896   

       ZXDB      ZXDC    ZYG11A    ZYG11B       ZYX     ZZEF1      ZZZ3  
0  30.98129  32.38442  28.01561  31.24379  33.81903  33.22469  31.23383  
1  30.74475  32.09470  26.32526  32.70057  33.67262  33.10198  32.44643  
2  30.15898  31.69473  26.33098  32.68330  33.96047  32.97135  32.20607  
3  30.25757  31.90774  27.53819  32.64194  34.54254  33.24885  32.78278  
4  30.17101  31.01545  21.45312  32.86620  34.24375  34.86720  32.73361  

[5 rows x 43921 columns]

In [3]:
X = data.iloc[:,28:43921  ] 
Y = [] # Target column
# For each entry I classified it by its PFS value.
for i in range (len(data)):
    if data.PFS[i]<3: # If PFS is lower than 3 months, I will consider it as NonResponder (NR)
        Y.append(0)
    elif data.PFS[i]<6:
        Y.append(1)
    else:
        Y.append(2)# If PFS is over 3 months, I will consider it as Responder (R)

X

5S_rRNA        7SK       A1BG   A1BG-AS1       A1CF        A2M  \
0    21.038652  35.199603  30.187983  22.999432  33.643965  37.130851   
1    21.038652  38.183943  30.483638  25.581769  28.866645  37.945043   
2    21.038652  37.141292  30.092851  26.933385  26.684228  36.851946   
3    21.038652  36.447015  30.975010  26.683128  32.521495  38.453517   
4    21.038652  37.623923  26.915750  22.999432  23.219176  38.931987   
..         ...        ...        ...        ...        ...        ...   
176  21.038043  36.338729  30.954407  27.310879  26.161567  38.376185   
177  21.038043  38.248915  33.110149  26.793199  26.161567  36.537388   
178  21.038043  35.884812  32.880283  25.659842  31.822942  38.265866   
179  21.038043  35.283776  30.658715  27.533890  32.930512  36.882090   
180  21.038043  36.694546  27.118678  17.788726  33.128697  35.626724   

       A2M-AS1      A2ML1  A2ML1-AS1      A2MP1  ...    ZWILCH     ZWINT  \
0    22.705126  22.869853  21.076515  21.271282  ...  33.26816  30.04056   
1    27.797609  24.142100  21.076515  21.271282  ...  31.53633  29.94062   
2    22.705126  30.406352  21.076515  21.271282  ...  30.74474  31.95812   
3    26.337846  28.229357  21.076515  21.271282  ...  31.63196  30.71732   
4    22.705126  22.869853  21.076515  21.271282  ...  31.75620  30.75149   
..         ...        ...        ...        ...  ...       ...       ...   
176  25.971821  24.438322  21.076088  21.056491  ...  31.62442  30.78532   
177  26.388265  24.438322  21.076088  21.056491  ...  31.40147  31.50200   
178  26.504307  24.438322  21.076088  21.056491  ...  31.21094  30.91066   
179  26.303147  24.438322  21.076088  21.056491  ...  31.12324  28.76312   
180  20.654847  24.438322  21.076088  21.056491  ...  32.79170  33.26885   

         ZXDA      ZXDB      ZXDC    ZYG11A    ZYG11B       ZYX     ZZEF1  \
0    30.36292  30.98129  32.38442  28.01561  31.24379  33.81903  33.22469   
1    30.80829  30.74475  32.09470  26.32526  32.70057  33.67262  33.10198   
2    30.73898  30.15898  31.69473  26.33098  32.68330  33.96047  32.97135   
3    31.09654  30.25757  31.90774  27.53819  32.64194  34.54254  33.24885   
4    30.55896  30.17101  31.01545  21.45312  32.86620  34.24375  34.86720   
..        ...       ...       ...       ...       ...       ...       ...   
176  30.86517  30.92600  31.53239  23.65585  32.42073  34.41045  33.21697   
177  29.96535  30.21446  31.49627  28.04168  32.19568  32.69615  32.18970   
178  31.35764  30.99788  31.45772  23.65585  32.36832  35.02409  34.26388   
179  31.48891  30.27351  32.88316  23.65585  31.76924  34.07224  34.35116   
180  31.30271  30.72641  31.65005  23.65585  30.82798  34.72915  33.65903   

         ZZZ3  
0    31.23383  
1    32.44643  
2    32.20607  
3    32.78278  
4    32.73361  
..        ...  
176  32.22166  
177  32.59554  
178  32.82148  
179  31.98965  
180  32.91379  

[181 rows x 43893 columns]

### 3. Train-Test dataset split

In [4]:
XTrain, XTest, yTrain, yTest = train_test_split(X, Y, test_size=0.15, random_state=125, stratify=Y)

print('Training set size:', len(XTrain))
print('Target column size of the training set:', len(yTrain))
print('Test set size:', len(XTest))
print('Target column size of the test set:', len(yTest))

Training set size: 153
Target column size of the training set: 153
Test set size: 28
Target column size of the test set: 28


### 4. Select the parameters of the model and fit it

In [5]:
param_grid = {'max_iter': [200, 500, 1000],
            'activation': ['identity', 'logistic', 'tanh', 'relu'],
            'random_state': [125],
            'max_fun': [300, 500,1000, 5000, 10000, 15000, 20000],
            'hidden_layer_sizes': [3,5],
            'solver': ['lbfgs']}

# I created a GridSearchCV which allows us to systematically evaluate and select the parameters of our model.
# By indicating a model and the parameters to test, you can evaluate the performance of the first one based on the
# seconds through cross validation.
clf = GridSearchCV(MLPClassifier(), param_grid, cv =5)

clf.fit(XTrain , yTrain)


C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\sandr

GridSearchCV(cv=5, estimator=MLPClassifier(),
             param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'],
                         'hidden_layer_sizes': [3, 5],
                         'max_fun': [300, 500, 1000, 5000, 10000, 15000, 20000],
                         'max_iter': [200, 500, 1000], 'random_state': [125],
                         'solver': ['lbfgs']})

In [6]:
print("Best estimate of parameters according to GridSearchCV:")
model = clf.best_estimator_
# Fit the model with the best parameters
model.fit(XTrain , yTrain)

Best estimate of parameters according to GridSearchCV:


C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


MLPClassifier(activation='tanh', hidden_layer_sizes=3, max_fun=300,
              random_state=125, solver='lbfgs')

In [7]:
print("Best result of the cross validation of the model with the best paramters:" +str(clf.best_score_))

Best result of the cross validation of the model with the best paramters:0.5027956989247311


### 5. Prediction

In [8]:
# Making predictions with the optimal model on the training dataset
yhatTrain = model.predict(XTrain)
contTrain = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTrain),1) :
    if (yhatTrain[i] == yTrain[i]):
        contTrain = contTrain + 1

In [9]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(XTest)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTest),1) :
    if (yhatTest[i] == yTest[i]):
        contTest = contTest + 1

In [10]:
print('Final accuracy on the training dataset: ' + str(contTrain/len(yTrain)))
print('Final accuracy on the testing dataset: ' + str(contTest/len(yTest)))

Final accuracy on the training dataset: 0.7450980392156863
Final accuracy on the testing dataset: 0.4642857142857143


In [11]:
from sklearn.metrics import classification_report,confusion_matrix

print('----------------Confusion Matrix (Training)------------------')
print(confusion_matrix(yTrain,yhatTrain))
print('Input data:  ' + str(np.array(yTrain)))
print('Prediction:        ' +str(yhatTrain))

----------------Confusion Matrix (Training)------------------
[[72  0  0]
 [ 6  0 20]
 [13  0 42]]
Input data:  [1 2 2 2 0 2 2 2 0 0 0 2 0 0 0 2 2 0 0 0 2 0 2 0 0 0 2 1 0 0 0 1 0 0 0 0 1
 1 1 2 2 2 2 0 1 2 0 0 2 2 1 2 1 0 2 0 2 2 2 0 0 2 0 2 2 0 2 2 0 0 0 0 0 0
 1 2 2 0 2 0 0 0 2 0 0 0 1 0 0 1 0 2 2 0 0 1 1 2 1 2 1 0 0 2 0 2 0 0 1 0 1
 0 0 2 0 0 2 2 2 2 1 0 2 2 2 1 0 0 1 0 0 1 0 2 2 1 0 2 0 0 2 0 1 0 0 0 2 2
 2 1 2 0 1]
Prediction:        [2 0 2 2 0 2 2 0 0 0 0 2 0 0 0 2 2 0 0 0 2 0 0 0 0 0 2 2 0 0 0 2 0 0 0 0 2
 0 2 2 2 0 2 0 0 0 0 0 0 2 0 2 0 0 2 0 2 0 2 0 0 2 0 2 2 0 2 2 0 0 0 0 0 0
 2 2 2 0 2 0 0 0 2 0 0 0 2 0 0 2 0 0 2 0 0 0 2 2 2 0 2 0 0 2 0 2 0 0 2 0 2
 0 0 2 0 0 2 2 0 0 2 0 2 2 2 0 0 0 2 0 0 2 0 2 0 2 0 2 0 0 2 0 2 0 0 0 2 2
 0 2 2 0 2]


In [12]:
print(classification_report(yTrain,yhatTrain))

              precision    recall  f1-score   support

           0       0.79      1.00      0.88        72
           1       0.00      0.00      0.00        26
           2       0.68      0.76      0.72        55

    accuracy                           0.75       153
   macro avg       0.49      0.59      0.53       153
weighted avg       0.62      0.75      0.67       153



C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1308: Unde

In [13]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(yTest,yhatTest))
print('Input data:  ' + str(np.array(yTest)))
print('Prediction:        ' +str(yhatTest))

----------------Confusion Matrix (Test)------------------
[[7 0 6]
 [3 0 2]
 [4 0 6]]
Input data:  [0 2 2 1 2 0 2 0 0 1 0 1 2 2 0 2 0 0 1 2 0 0 0 2 2 1 0 0]
Prediction:        [0 2 0 0 2 2 2 2 0 0 0 2 0 2 2 0 2 0 0 2 0 0 2 2 0 2 0 2]


In [14]:
print(classification_report(yTest,yhatTest))

              precision    recall  f1-score   support

           0       0.50      0.54      0.52        13
           1       0.00      0.00      0.00         5
           2       0.43      0.60      0.50        10

    accuracy                           0.46        28
   macro avg       0.31      0.38      0.34        28
weighted avg       0.39      0.46      0.42        28



C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\metrics\_classification.py:1308: Unde