# Classification model using Multilayer Perceptron

### 1. Import libraries

In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

### 2. Upload Clinic data

In [6]:
path ="../../../../Data_preprocessing/RNA_post_autoencoder/encoded_data_multiclass_200.csv"
data = pd.read_csv(path)
data.reset_index
data.round(4)
data=data.iloc[:,1:202  ] 
data.head()

Target         0         1         2         3         4         5  \
0       2  0.436414 -1.576482  2.176638  1.046650 -0.967788 -0.332760   
1       1 -0.032149 -0.995621  1.888060  1.284731  0.079140  0.064063   
2       2  0.476933 -2.010775  1.879018  0.383090  0.207985 -0.992632   
3       0  0.547395 -0.711453  1.527116  1.052659  0.077064  0.006284   
4       1 -0.624718 -2.406139  2.824231 -0.012635 -1.314704 -0.748785   

          6         7         8  ...       190       191       192       193  \
0 -0.586029  1.430570 -0.895583  ... -0.928760  0.075799 -0.263159 -0.655430   
1 -0.199813  1.521006  0.564534  ...  0.483468 -0.893442  0.575146 -0.778792   
2  0.020097  0.387833 -1.122965  ...  0.017044  0.602836 -1.916266  1.144584   
3 -0.112697  1.186751  0.211799  ...  0.633414 -0.524010  0.202187 -0.838269   
4  0.687588  2.262579 -0.263327  ...  0.454670 -0.789785 -0.452545  1.738423   

        194       195       196       197       198       199  
0  1.285033  1.158913 -0.501004 -1.361494  0.612884  0.746754  
1  0.324170  0.177823 -1.233956 -1.483099 -0.341608 -0.996777  
2  1.069570  0.535930 -0.897938 -1.371405 -0.231251 -0.274360  
3 -0.029785  0.492356 -1.486459 -1.970962  0.530672 -0.985897  
4  0.543774  0.753638 -1.839001 -0.347618  0.589409 -1.081583  

[5 rows x 201 columns]

In [7]:
Y = data.Target # Target column

X = data.iloc[:,1:202] # I selected all the columns by removing the Unnamed column (row id) and the Target column.


print(X)
print('Numero de pacientes: ',len(Y))

            0         1         2         3         4         5         6  \
0    0.436414 -1.576482  2.176638  1.046650 -0.967788 -0.332760 -0.586029   
1   -0.032149 -0.995621  1.888060  1.284731  0.079140  0.064063 -0.199813   
2    0.476933 -2.010775  1.879018  0.383090  0.207985 -0.992632  0.020097   
3    0.547395 -0.711453  1.527116  1.052659  0.077064  0.006284 -0.112697   
4   -0.624718 -2.406139  2.824231 -0.012635 -1.314704 -0.748785  0.687588   
..        ...       ...       ...       ...       ...       ...       ...   
176  0.152039 -1.448956  1.631890  0.438465 -0.797802 -0.450635 -0.031156   
177  1.139950 -1.364696  0.767903  0.954542  0.358079 -0.439770  0.195097   
178  0.291298 -2.023891  1.954019  1.072944 -0.490579 -0.466329  0.094765   
179  0.102469 -0.451807  1.057516  0.105644 -0.375693 -0.814802  0.114747   
180  0.794935 -1.928761  0.771840  0.929302 -0.237190 -0.890115  0.127341   

            7         8         9  ...       190       191       192  \
0  

### 3. Train-Test dataset split

In [8]:
XTrain, XTest, yTrain, yTest = train_test_split(X, Y, test_size=0.20, random_state=125, stratify=Y)
yTrain=yTrain.to_numpy()
yTest=yTest.to_numpy()
print('Training set size:', len(XTrain))
print('Target column size of the training set:', len(yTrain))
print('Test set size:', len(XTest))
print('Target column size of the test set:', len(yTest))

Training set size: 144
Target column size of the training set: 144
Test set size: 37
Target column size of the test set: 37


In [9]:
param_grid = {'max_iter': [200000, 500000, 10000000],
            'activation': ['identity', 'logistic', 'tanh', 'relu'],
            'random_state': [125],
            'max_fun': [300, 500,1000, 5000, 10000, 15000, 20000],
            'hidden_layer_sizes': [3,5],
            'solver': ['lbfgs']}

# I created a GridSearchCV which allows us to systematically evaluate and select the parameters of our model.
# By indicating a model and the parameters to test, you can evaluate the performance of the first one based on the
# seconds through cross validation.
clf = GridSearchCV(MLPClassifier(), param_grid, cv =5)

clf.fit(XTrain , yTrain)


C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lb

GridSearchCV(cv=5, estimator=MLPClassifier(),
             param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'],
                         'hidden_layer_sizes': [3, 5],
                         'max_fun': [300, 500, 1000, 5000, 10000, 15000, 20000],
                         'max_iter': [200000, 500000, 10000000],
                         'random_state': [125], 'solver': ['lbfgs']})

In [10]:
print("Best estimate of parameters according to GridSearchCV:")
print(clf.best_estimator_)
# Fit the model with the best parameters
model = clf.best_estimator_

Best estimate of parameters according to GridSearchCV:
MLPClassifier(activation='tanh', hidden_layer_sizes=3, max_fun=5000,
              max_iter=200000, random_state=125, solver='lbfgs')


In [11]:
print("Best result of the cross validation of the model with the best paramters:" +str(clf.best_score_))

Best result of the cross validation of the model with the best paramters:0.5275862068965517


### 5. Prediction

In [12]:
# Making predictions with the optimal model on the training dataset
yhatTrain = model.predict(XTrain)
contTrain = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTrain),1) :
    if (yhatTrain[i] == yTrain[i]):
        contTrain = contTrain + 1

In [13]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(XTest)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTest),1) :
    if (yhatTest[i] == yTest[i]):
        contTest = contTest + 1


### 6. Results

In [14]:
print('Final accuracy on the training dataset:' + str(contTrain/len(yTrain)))
print('Final accuracy on the testing dataset: ' + str(contTest/len(yTest)))

Final accuracy on the training dataset:0.8472222222222222
Final accuracy on the testing dataset: 0.32432432432432434


In [15]:
from sklearn.metrics import classification_report,confusion_matrix

print('----------------Confusion Matrix (Training)------------------')
print(confusion_matrix(yTrain,yhatTrain))
print('Input data:  ' + str(np.array(yTrain)))
print('Prediction:        ' +str(yhatTrain))

----------------Confusion Matrix (Training)------------------
[[63  3  1]
 [ 4 17  4]
 [10  0 42]]
Input data:  [1 0 2 0 2 2 0 0 2 0 2 0 1 0 2 2 0 2 2 2 0 0 0 2 0 0 0 0 1 1 2 2 2 2 0 1 2
 0 0 2 1 2 2 1 0 0 2 2 1 0 0 0 2 0 0 2 0 2 1 2 0 2 1 0 0 0 0 2 2 2 0 2 0 0
 0 2 0 2 0 0 0 1 2 0 0 1 2 2 1 1 0 2 0 2 0 0 1 0 1 0 0 2 0 0 2 2 2 1 0 2 2
 1 2 0 1 0 0 0 2 0 1 0 2 0 0 2 1 1 0 0 0 2 0 1 0 0 0 2 2 2 1 2 0 1]
Prediction:        [1 1 2 0 0 2 0 0 0 0 2 0 0 0 0 2 0 2 2 2 1 0 0 2 0 0 0 0 1 0 2 2 2 2 0 2 2
 0 0 0 0 2 2 1 0 0 2 0 1 0 0 0 0 0 0 0 0 2 1 0 0 2 1 0 0 0 0 2 2 2 0 2 0 1
 0 2 0 2 0 0 0 1 2 0 0 1 2 2 1 1 0 2 0 2 0 0 1 0 1 2 0 2 0 0 2 2 2 1 0 2 2
 1 2 0 2 0 0 0 0 0 1 0 2 0 0 2 1 2 0 0 0 2 0 1 0 0 0 2 2 2 0 0 0 2]


In [16]:
print(classification_report(yTrain,yhatTrain))

              precision    recall  f1-score   support

           0       0.82      0.94      0.88        67
           1       0.85      0.68      0.76        25
           2       0.89      0.81      0.85        52

    accuracy                           0.85       144
   macro avg       0.85      0.81      0.83       144
weighted avg       0.85      0.85      0.84       144



In [17]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(yTest,yhatTest))
print('Input data:  ' + str(np.array(yTest)))
print('Prediction:        ' +str(yhatTest))

----------------Confusion Matrix (Test)------------------
[[7 5 6]
 [3 1 2]
 [5 4 4]]
Input data:  [0 1 0 2 0 2 1 0 1 0 2 2 1 2 2 0 1 2 0 0 0 2 1 0 0 2 0 2 2 0 0 0 2 2 0 0 0]
Prediction:        [0 2 2 0 2 2 1 0 0 1 1 2 0 2 2 0 0 0 0 2 1 1 2 1 0 1 1 0 1 1 0 2 0 0 2 2 0]


In [18]:
print(classification_report(yTest,yhatTest))

              precision    recall  f1-score   support

           0       0.47      0.39      0.42        18
           1       0.10      0.17      0.12         6
           2       0.33      0.31      0.32        13

    accuracy                           0.32        37
   macro avg       0.30      0.29      0.29        37
weighted avg       0.36      0.32      0.34        37

