# Classification model using Multilayer Perceptron

### 1. Import libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV

### 2. Upload Clinic data

In [2]:
path ="../../../../Data_preprocessing/RNA_post_autoencoder/encoded_data_multiclass_200_review.csv"
data = pd.read_csv(path)
data.reset_index
data.round(4)
data=data.iloc[:,1:202  ] 
data.head()

Target         0         1         2         3         4         5  \
0       2  0.090383 -0.649882 -0.316971  0.177905 -0.953876  0.335641   
1       1  0.477048 -2.020710  1.091671  1.287272 -0.363761  0.754296   
2       2  0.635105 -1.455384  1.860401  0.632697 -0.930232  0.295499   
3       0  0.961507 -2.004696  0.853696  1.317209 -0.583800  1.132528   
4       1 -0.525586 -1.646895  0.137172  0.377502 -0.305213  0.422324   

          6         7         8  ...       190       191       192       193  \
0  0.547794 -0.553937  0.110278  ...  2.092920 -0.902635 -1.113107 -0.413884   
1  0.507876  0.777283 -1.120030  ...  0.697679  0.224512 -1.192957  0.061010   
2  0.756204  0.523225 -2.107392  ...  0.579307 -1.044159 -1.480045 -0.010595   
3  0.550134  0.217618 -1.552470  ...  1.360498 -0.087889 -1.876129  0.023887   
4  0.282720 -0.810817 -2.396630  ...  1.815167 -2.681982 -0.615784 -0.857696   

        194       195       196       197       198       199  
0 -0.589024  1.206955 -0.300583  0.270012 -0.130936  0.180399  
1  0.960343  0.241303  0.719193  0.983675 -1.161567 -0.246087  
2  0.363854  0.695291 -0.760165  0.963433 -1.901634 -0.315921  
3  0.442273  1.212686 -0.353484  0.908717 -1.918175 -0.237121  
4 -2.062510  0.060919 -0.826840  1.522230 -1.236770  0.269057  

[5 rows x 201 columns]

In [3]:
Y = data.Target # Target column

X = data.iloc[:,1:202] # I selected all the columns by removing the Unnamed column (row id) and the Target column.


print(X)
print('Numero de pacientes: ',len(Y))

            0         1         2         3         4         5         6  \
0    0.090383 -0.649882 -0.316971  0.177905 -0.953876  0.335641  0.547794   
1    0.477048 -2.020710  1.091671  1.287272 -0.363761  0.754296  0.507876   
2    0.635105 -1.455384  1.860401  0.632697 -0.930232  0.295499  0.756204   
3    0.961507 -2.004696  0.853696  1.317209 -0.583800  1.132528  0.550134   
4   -0.525586 -1.646895  0.137172  0.377502 -0.305213  0.422324  0.282720   
..        ...       ...       ...       ...       ...       ...       ...   
176  0.236947 -1.546189  0.735707  0.337749 -0.865903  0.177455  0.514749   
177  0.524165 -2.116409 -0.105561  0.699807 -0.680601  0.442997  0.912442   
178  0.392108 -1.538342  1.038728  0.582032 -0.505431 -0.056508  0.191502   
179 -0.151722 -1.736164  0.687119  0.422451 -0.804183 -0.165308  0.940421   
180  0.356281 -1.524765  0.030108 -0.003902 -0.441868 -0.106647  0.691161   

            7         8         9  ...       190       191       192  \
0  

### 3. Train-Test dataset split

In [4]:
XTrain, XTest, yTrain, yTest = train_test_split(X, Y, test_size=0.20, random_state=125, stratify=Y)
yTrain=yTrain.to_numpy()
yTest=yTest.to_numpy()
print('Training set size:', len(XTrain))
print('Target column size of the training set:', len(yTrain))
print('Test set size:', len(XTest))
print('Target column size of the test set:', len(yTest))

Training set size: 144
Target column size of the training set: 144
Test set size: 37
Target column size of the test set: 37


In [5]:
param_grid = {'max_iter': [200000, 500000, 10000000],
            'activation': ['identity', 'logistic', 'tanh', 'relu'],
            'random_state': [125],
            'max_fun': [300, 500,1000, 5000, 10000, 15000, 20000],
            'hidden_layer_sizes': [3,5],
            'solver': ['lbfgs']}

# I created a GridSearchCV which allows us to systematically evaluate and select the parameters of our model.
# By indicating a model and the parameters to test, you can evaluate the performance of the first one based on the
# seconds through cross validation.
clf = GridSearchCV(MLPClassifier(), param_grid, cv =5)

clf.fit(XTrain , yTrain)


C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
C:\Users\sandr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\neural_network\_multilayer_perceptron.py:549: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of f AND g EVALUATIONS EXCEEDS LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lb

GridSearchCV(cv=5, estimator=MLPClassifier(),
             param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'],
                         'hidden_layer_sizes': [3, 5],
                         'max_fun': [300, 500, 1000, 5000, 10000, 15000, 20000],
                         'max_iter': [200000, 500000, 10000000],
                         'random_state': [125], 'solver': ['lbfgs']})

In [6]:
print("Best estimate of parameters according to GridSearchCV:")
print(clf.best_estimator_)
# Fit the model with the best parameters
model = clf.best_estimator_

Best estimate of parameters according to GridSearchCV:
MLPClassifier(hidden_layer_sizes=3, max_fun=300, max_iter=200000,
              random_state=125, solver='lbfgs')


In [7]:
print("Best result of the cross validation of the model with the best paramters:" +str(clf.best_score_))

Best result of the cross validation of the model with the best paramters:0.4935960591133005


### 5. Prediction

In [8]:
# Making predictions with the optimal model on the training dataset
yhatTrain = model.predict(XTrain)
contTrain = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTrain),1) :
    if (yhatTrain[i] == yTrain[i]):
        contTrain = contTrain + 1

In [9]:
# Making predictions with the optimal model on the test dataset
yhatTest = model.predict(XTest)
contTest = 0

# Comparing with the Target column and check how many hits there have been
for i in range(0,len(yTest),1) :
    if (yhatTest[i] == yTest[i]):
        contTest = contTest + 1


### 6. Results

In [10]:
print('Final accuracy on the training dataset:' + str(contTrain/len(yTrain)))
print('Final accuracy on the testing dataset: ' + str(contTest/len(yTest)))

Final accuracy on the training dataset:0.7777777777777778
Final accuracy on the testing dataset: 0.43243243243243246


In [11]:
from sklearn.metrics import classification_report,confusion_matrix

print('----------------Confusion Matrix (Training)------------------')
print(confusion_matrix(yTrain,yhatTrain))
print('Input data:  ' + str(np.array(yTrain)))
print('Prediction:        ' +str(yhatTrain))

----------------Confusion Matrix (Training)------------------
[[55  0 12]
 [ 7  5 13]
 [ 0  0 52]]
Input data:  [1 0 2 0 2 2 0 0 2 0 2 0 1 0 2 2 0 2 2 2 0 0 0 2 0 0 0 0 1 1 2 2 2 2 0 1 2
 0 0 2 1 2 2 1 0 0 2 2 1 0 0 0 2 0 0 2 0 2 1 2 0 2 1 0 0 0 0 2 2 2 0 2 0 0
 0 2 0 2 0 0 0 1 2 0 0 1 2 2 1 1 0 2 0 2 0 0 1 0 1 0 0 2 0 0 2 2 2 1 0 2 2
 1 2 0 1 0 0 0 2 0 1 0 2 0 0 2 1 1 0 0 0 2 0 1 0 0 0 2 2 2 1 2 0 1]
Prediction:        [0 2 2 0 2 2 0 0 2 0 2 2 2 0 2 2 0 2 2 2 0 0 0 2 0 0 2 0 2 2 2 2 2 2 0 0 2
 2 0 2 2 2 2 2 2 0 2 2 2 0 0 0 2 0 0 2 0 2 2 2 0 2 1 0 0 0 0 2 2 2 0 2 0 2
 0 2 0 2 2 0 0 2 2 0 0 2 2 2 2 0 0 2 2 2 0 2 1 0 2 0 2 2 0 0 2 2 2 0 0 2 2
 1 2 0 0 0 0 0 2 0 2 0 2 0 0 2 2 1 0 0 0 2 0 1 0 2 2 2 2 2 0 2 0 0]


In [12]:
print(classification_report(yTrain,yhatTrain))

              precision    recall  f1-score   support

           0       0.89      0.82      0.85        67
           1       1.00      0.20      0.33        25
           2       0.68      1.00      0.81        52

    accuracy                           0.78       144
   macro avg       0.85      0.67      0.66       144
weighted avg       0.83      0.78      0.75       144



In [13]:
print('----------------Confusion Matrix (Test)------------------')
print(confusion_matrix(yTest,yhatTest))
print('Input data:  ' + str(np.array(yTest)))
print('Prediction:        ' +str(yhatTest))

----------------Confusion Matrix (Test)------------------
[[ 7  0 11]
 [ 1  2  3]
 [ 4  2  7]]
Input data:  [0 1 0 2 0 2 1 0 1 0 2 2 1 2 2 0 1 2 0 0 0 2 1 0 0 2 0 2 2 0 0 0 2 2 0 0 0]
Prediction:        [0 2 0 2 2 2 2 2 0 0 1 1 1 0 0 2 1 2 0 2 2 2 2 2 0 2 2 0 2 2 2 0 0 2 2 2 0]


In [14]:
print(classification_report(yTest,yhatTest))

              precision    recall  f1-score   support

           0       0.58      0.39      0.47        18
           1       0.50      0.33      0.40         6
           2       0.33      0.54      0.41        13

    accuracy                           0.43        37
   macro avg       0.47      0.42      0.43        37
weighted avg       0.48      0.43      0.44        37

